//! The CLI reference page, walked from the clap definition of `b10x-loom` (`b10x_loom_cli::Cli`).

use clap::CommandFactory;

use crate::{SOURCE, cell, front_matter_with};

/// Where the CLI reference lands, relative to the repository root.
pub const PAGE: &str = "website/docs/reference/cli.md";

/// Every subcommand below `command`, depth first, without clap's `help`.
fn commands(command: &clap::Command, out: &mut Vec<clap::Command>) {
    for sub in command.get_subcommands() {
        if sub.get_name() == "help" {
            continue;
        }
        out.push(sub.clone());
        commands(sub, out);
    }
}

/// The heading anchor Docusaurus gives `## \`b10x-loom run\``.
fn anchor(command: &clap::Command) -> String {
    command
        .get_bin_name()
        .unwrap_or(command.get_name())
        .replace(' ', "-")
}

fn text(value: Option<&clap::builder::StyledStr>) -> String {
    value.map(ToString::to_string).unwrap_or_default()
}

/// One row per argument of `command`: how it is written, whether it is required, its default and
/// its help.
fn arguments(command: &clap::Command) -> Vec<[String; 4]> {
    command
        .get_arguments()
        .filter(|arg| !matches!(arg.get_id().as_str(), "help" | "version"))
        .map(|arg| {
            let value = arg
                .get_value_names()
                .and_then(|names| names.first().map(ToString::to_string))
                .unwrap_or_else(|| arg.get_id().as_str().to_uppercase());
            let written = match arg.get_long() {
                Some(long) if !arg.get_action().takes_values() => format!("--{long}"),
                Some(long) => format!("--{long} <{value}>"),
                None => format!("<{value}>"),
            };
            let defaults: Vec<String> = arg
                .get_default_values()
                .iter()
                .map(|default| default.to_string_lossy().into_owned())
                .collect();
            [
                format!("`{written}`"),
                if arg.is_required_set() { "yes" } else { "no" }.to_owned(),
                if defaults.is_empty() {
                    "none".to_owned()
                } else {
                    format!("`{}`", defaults.join(", "))
                },
                cell(&text(arg.get_long_help().or(arg.get_help()))),
            ]
        })
        .collect()
}

/// The CLI reference page for the command line `root`.
pub fn page_for(mut root: clap::Command) -> String {
    root.build();
    let name = root.get_name().to_owned();
    let mut all = Vec::new();
    commands(&root, &mut all);

    let mut out = front_matter_with(
        &format!("{name} CLI reference"),
        &format!("{name} CLI"),
        &format!(
            "Every command and option of the {name} command line, generated from its definition."
        ),
        Some(1),
    );
    out.push_str(&format!(
        "# `{name}`\n\nGenerated from the clap definition of the `{name}` command line in \
         [`crates/loom-cli/src/lib.rs`]({SOURCE}/crates/loom-cli/src/lib.rs) by `loom-docs`. It \
         lists only commands that exist.\n\n> {}\n\n`{name} --version` prints its version, \
         and `--help` after any command prints the text below.\n\n## Commands\n\n\
         | Command | What it does |\n|---|---|\n",
        cell(&text(root.get_about()))
    ));
    for command in &all {
        let written = command.get_bin_name().unwrap_or(command.get_name());
        out.push_str(&format!(
            "| [`{written}`](#{}) | {} |\n",
            anchor(command),
            cell(&text(command.get_about()))
        ));
    }
    for command in &mut all {
        let written = command
            .get_bin_name()
            .unwrap_or(command.get_name())
            .to_owned();
        out.push_str(&format!(
            "\n## `{written}`\n\n{}\n\n```text\n{}\n```\n",
            cell(&text(command.get_long_about().or(command.get_about()))),
            command.render_usage().to_string().trim_end()
        ));
        let rows = arguments(command);
        if !rows.is_empty() {
            out.push_str("\n| Argument | Required | Default | Meaning |\n|---|---|---|---|\n");
            for row in rows {
                out.push_str(&format!("| {} |\n", row.join(" | ")));
            }
        }
        let after = text(command.get_after_long_help().or(command.get_after_help()));
        if !after.is_empty() {
            out.push_str(&format!("\n```text\n{}\n```\n", after.trim_end()));
        }
    }
    out
}

/// The CLI reference page for `b10x-loom`.
pub fn page() -> String {
    page_for(b10x_loom_cli::Cli::command())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_command_option_default_and_exit_status_is_listed() {
        let page = page();
        assert!(page.contains("# generated by loom-docs, do not edit"));
        assert!(page.contains("custom_edit_url: null"));
        assert!(page.contains("| [`b10x-loom run`](#b10x-loom-run) |"));
        assert!(page.contains("## `b10x-loom run`"));
        assert!(page.contains("Usage: b10x-loom run [OPTIONS] <INTENT>"));
        assert!(page.contains("| `--workspace <DIR>` | no | none |"));
        assert!(page.contains("| `--test-cmd <CMD>` | no | `cargo test` |"));
        assert!(page.contains("| `--max-steps <N>` | no | `20` |"));
        assert!(page.contains("| `<INTENT>` | yes | none | What to do, as given |"));
        assert!(page.contains("0  the query completed (Completed) or the run reached its human gate (ApprovalRequired)"));
        assert!(page.contains("| `--replace` | no | `false` |"));
        assert!(!page.contains("--replace <REPLACE>"));
        assert!(!page.contains("b10x-loom help"));
    }
}
