#![forbid(unsafe_code)]
//! Generates the derivable part of the documentation site as Markdown under
//! `website/docs/reference/`, checks it for drift, and binds a built site to its source commit.
//! The site build itself is Docusaurus.
//!
//! It generates three references:
//!
//! - the CLI reference (`reference/cli.md`), walked from the clap definition of `b10x-loom`;
//! - the crate list (`reference/crates.md`), from `cargo metadata --no-deps`;
//! - the ESS domain reference (`reference/ess/`) of the `loom` (`ess/`) and `intake`
//!   (`ess/intake/`) systems: Markdown pages from `ess generate --kind docs`, and one
//!   `b10x-domain-graph/1` document per domain from `ess specify compile`.
//!
//! Commission's own system (`ess/commission/`) has its reference pages from
//! `loom-commission-docs`.
mod cli;
mod crates;
mod graph;

use std::{
    collections::BTreeMap,
    fs,
    path::{Path, PathBuf},
    process::Command,
};

use anyhow::{Context, Result, bail, ensure};
use clap::{Parser, Subcommand};

/// The first line of every generated page's front matter.
const FRONT_MATTER_HEADER: &str = "# generated by loom-docs, do not edit";
/// The line every generated Markdown page carries directly after its front matter.
const HEADER: &str = "<!-- generated by loom-docs, do not edit -->";
/// A file in the repository on GitHub, by path.
const SOURCE: &str = "https://github.com/beyond10x/loom/blob/main";
/// A directory in the repository on GitHub, by path.
const TREE: &str = "https://github.com/beyond10x/loom/tree/main";
/// The ESS systems whose domains the reference lists, relative to the repository root.
const ESS_SYSTEMS: [&str; 2] = ["ess", "ess/intake"];
/// The same line in an MDX page, where HTML comments are not allowed.
const MDX_HEADER: &str = "{/* generated by loom-docs, do not edit */}";
/// Where the ESS reference pages land, relative to the repository root.
const ESS_REFERENCE: &str = "website/docs/reference/ess";
/// Where the domain graphs land, relative to the repository root.
const ESS_DATA: &str = "website/data/ess";
/// Every documentation page, generated or written by hand, relative to the repository root.
const DOCS: &str = "website/docs";

/// Whether `line` matches `^:::[a-z]+ +\S`: an admonition whose title is not in brackets, which
/// Docusaurus prints as raw text.
fn is_raw_admonition(line: &str) -> bool {
    let Some(rest) = line.strip_prefix(":::") else {
        return false;
    };
    let kind = rest.bytes().take_while(u8::is_ascii_lowercase).count();
    let rest = &rest[kind..];
    let spaces = rest.bytes().take_while(|b| *b == b' ').count();
    kind > 0
        && spaces > 0
        && rest[spaces..]
            .chars()
            .next()
            .is_some_and(|c| !c.is_whitespace())
}

/// `file:line` of every raw admonition title in the Markdown and MDX pages under `dir`.
fn raw_admonitions(dir: &Path) -> Result<Vec<String>> {
    let mut found = Vec::new();
    let mut entries: Vec<_> = fs::read_dir(dir)
        .with_context(|| format!("reading {}", dir.display()))?
        .collect::<Result<_, _>>()?;
    entries.sort_by_key(|entry| entry.path());
    for entry in entries {
        let path = entry.path();
        if path.is_dir() {
            found.extend(raw_admonitions(&path)?);
        } else if path
            .extension()
            .is_some_and(|ext| ext == "md" || ext == "mdx")
        {
            for (n, line) in fs::read_to_string(&path)?.lines().enumerate() {
                if is_raw_admonition(line) {
                    found.push(format!("{}:{}", path.display(), n + 1));
                }
            }
        }
    }
    Ok(found)
}

#[derive(Parser)]
#[command(about = "Generate and check the derived pages of the Loom documentation site")]
struct Cli {
    #[command(subcommand)]
    command: Action,
}

#[derive(Subcommand)]
enum Action {
    /// Regenerate website/docs/reference/ from the repository, or check it for drift.
    Generate {
        /// Write nothing; fail when a generated page is missing, stale or hand-edited.
        #[arg(long)]
        check: bool,
        /// Repository root.
        #[arg(long, default_value = ".")]
        root: PathBuf,
        /// The `ess` executable.
        #[arg(long, default_value = "ess")]
        ess: PathBuf,
    },
    /// Bind a built site to its source commit: write `.well-known/b10x-site.json` into it.
    Provenance {
        /// The built site, `website/build`.
        #[arg(long)]
        site: PathBuf,
        /// The full Git revision the site was built from.
        #[arg(long)]
        commit: String,
    },
}

/// The project-site publication record for one build of the `/loom/` site.
fn site_manifest(commit: &str) -> Result<String> {
    ensure!(
        commit.len() == 40
            && commit.bytes().all(|b| b.is_ascii_hexdigit())
            && commit != "0".repeat(40),
        "commit must be a nonzero full Git revision"
    );
    Ok(format!(
        "{{\n  \"baseUrl\": \"/loom/\",\n  \"commit\": \"{commit}\",\n  \"repository\": \"loom\",\n  \"schema\": \"b10x-project-site/v1\"\n}}"
    ))
}

fn write_provenance(site: &Path, commit: &str) -> Result<()> {
    let manifest = site_manifest(commit)?;
    ensure!(
        site.join("index.html").is_file(),
        "{} holds no built site",
        site.display()
    );
    fs::create_dir_all(site.join(".well-known"))?;
    fs::write(site.join(".well-known/b10x-site.json"), manifest)
        .context("writing site provenance")?;
    fs::write(site.join(".nojekyll"), "")?;
    Ok(())
}

/// Pages keyed by file name, in the order they are written.
type Pages = BTreeMap<String, String>;

/// Strip the leading HTML comment `ess generate` writes, returning the rest.
fn strip_ess_banner(page: &str) -> Result<&str> {
    let rest = page
        .strip_prefix("<!--")
        .context("ess page does not open with its provenance comment")?;
    let end = rest
        .find("-->")
        .context("ess provenance comment is not closed")?;
    Ok(rest[end + 3..].trim_start_matches('\n'))
}

/// The H1 title and the first paragraph after it.
fn title_and_summary(body: &str) -> Result<(String, String)> {
    let mut lines = body.lines();
    let title = lines
        .next()
        .and_then(|line| line.strip_prefix("# "))
        .context("ess page does not open with a level-one heading")?
        .trim()
        .to_owned();
    let summary = lines
        .skip_while(|line| line.trim().is_empty())
        .take_while(|line| !line.trim().is_empty())
        .collect::<Vec<_>>()
        .join(" ");
    ensure!(!summary.is_empty(), "ess page {title} has no summary");
    Ok((title, summary))
}

fn yaml_string(value: &str) -> String {
    format!("\"{}\"", value.replace('\\', "\\\\").replace('"', "\\\""))
}

/// `value` as one Markdown table cell: on one line, with `|` escaped.
fn cell(value: &str) -> String {
    value
        .split_whitespace()
        .collect::<Vec<_>>()
        .join(" ")
        .replace('|', "\\|")
}

/// The front matter of a generated page: the generator line, title, label, description, an
/// optional sidebar position, and no edit link.
fn front_matter_with(title: &str, label: &str, description: &str, position: Option<u32>) -> String {
    let position = position
        .map(|n| format!("sidebar_position: {n}\n"))
        .unwrap_or_default();
    format!(
        "---\n{FRONT_MATTER_HEADER}\ntitle: {}\nsidebar_label: {}\n{position}description: {}\ncustom_edit_url: null\n---\n\n",
        yaml_string(title),
        yaml_string(label),
        yaml_string(description),
    )
}

fn front_matter(title: &str, label: &str, description: &str, header: &str) -> String {
    front_matter_with(title, label, description, None) + header + "\n\n"
}

/// One domain page of `ess generate --kind docs`, rewritten as a site page.
fn domain_page(source: &str) -> Result<(String, String, String)> {
    let body = strip_ess_banner(source)?;
    let (title, summary) = title_and_summary(body)?;
    let body = body
        .replace(
            "[Back to the index](../index.md)",
            "[All domains](./index.mdx)",
        )
        .replace("`ess generate`", "`task docs-generate`");
    ensure!(
        !body.contains("](../"),
        "ess page {title} links outside the generated domain pages"
    );
    let page = front_matter(
        &format!("{title} domain"),
        &title,
        &format!("ESS reference for the {title} domain, generated from the specification."),
        HEADER,
    ) + &body;
    Ok((title, summary, page))
}

/// One domain as the index lists it.
struct DomainEntry {
    page: String,
    graph: String,
    title: String,
    summary: String,
}

/// The reference index: one `<DomainGraph>` per domain, then a link to its full page.
fn index_page(domains: &[DomainEntry]) -> String {
    let mut page = front_matter(
        "ESS specification",
        "ESS specification",
        "The Loom and intake specifications, domain by domain, generated from ess/ in the repository.",
        MDX_HEADER,
    );
    for (n, domain) in domains.iter().enumerate() {
        page.push_str(&format!(
            "import domainGraph{n} from '@site/data/ess/{}';\n",
            domain.graph
        ));
    }
    page.push_str("\n# ESS specification\n\n");
    page.push_str(
        "Loom is specified in ESS. This page and the domain pages below are generated by \
         `loom-docs` from two systems in the repository: `loom` in `ess/` and `intake` in \
         `ess/intake/`. The graphs come from `ess specify compile`, the pages from `ess generate \
         --kind docs`. They change when the specification changes, and `task check` fails if they \
         fall behind it.\n\nCommission's system, in `ess/commission/`, has its own reference: the \
         [domain model](../commission/domain-model.mdx) and its [value \
         types](../commission/types.mdx).\n",
    );
    for (n, domain) in domains.iter().enumerate() {
        page.push_str(&format!(
            "\n## {title}\n\n{summary}\n\n<DomainGraph data={{domainGraph{n}}} title=\"{title}\" />\n\n\
             [Read the {title} domain in full](./{file})\n",
            title = domain.title,
            summary = domain.summary,
            file = domain.page,
        ));
    }
    page
}

/// Generated files: directory relative to the repository root, then file name, then content.
type Outputs = BTreeMap<&'static str, Pages>;

fn run(ess: &Path, args: &[&std::ffi::OsStr]) -> Result<Vec<u8>> {
    let output = Command::new(ess)
        .args(args)
        .output()
        .with_context(|| format!("running {}", ess.display()))?;
    if !output.status.success() {
        bail!(
            "{} {} failed: {}",
            ess.display(),
            args.iter()
                .map(|arg| arg.to_string_lossy())
                .collect::<Vec<_>>()
                .join(" "),
            String::from_utf8_lossy(&output.stderr)
        );
    }
    Ok(output.stdout)
}

/// One system's domain graphs (keyed by file name) and its domain pages with their index entries.
fn ess_system(root: &Path, system: &str, ess: &Path) -> Result<(Pages, Pages, Vec<DomainEntry>)> {
    let spec = root.join(system);
    let model: serde_json::Value = serde_json::from_slice(&run(
        ess,
        &[
            "specify".as_ref(),
            "compile".as_ref(),
            "--path".as_ref(),
            spec.as_os_str(),
            "--format".as_ref(),
            "json".as_ref(),
        ],
    )?)
    .with_context(|| format!("parsing the compiled ESS model of {system}"))?;
    let mut data = Pages::new();
    for (domain, graph) in graph::domain_graphs(&model)? {
        let name = format!("{}.domain-graph.json", domain.replace('.', "-"));
        data.insert(name, serde_json::to_string_pretty(&graph)? + "\n");
    }

    let scratch = std::env::temp_dir().join(format!(
        "loom-docs-{}-{}",
        std::process::id(),
        system.replace('/', "-")
    ));
    if scratch.exists() {
        fs::remove_dir_all(&scratch)?;
    }
    let result = (|| {
        run(
            ess,
            &[
                "generate".as_ref(),
                "--kind".as_ref(),
                "docs".as_ref(),
                "--path".as_ref(),
                spec.as_os_str(),
                "--out".as_ref(),
                scratch.as_os_str(),
            ],
        )?;
        let dir = scratch.join("docs/domains");
        let mut files: Vec<_> = fs::read_dir(&dir)
            .with_context(|| format!("reading {}", dir.display()))?
            .collect::<Result<_, _>>()?;
        files.sort_by_key(|entry| entry.file_name());
        let mut pages = Pages::new();
        let mut index = Vec::new();
        for entry in files {
            let name = entry.file_name().to_string_lossy().into_owned();
            let Some(stem) = name.strip_suffix(".md") else {
                continue;
            };
            let graph = format!("{stem}.domain-graph.json");
            ensure!(
                data.contains_key(&graph),
                "ess page {name} has no domain in the compiled model of {system}"
            );
            let (title, summary, page) = domain_page(&fs::read_to_string(entry.path())?)?;
            index.push(DomainEntry {
                page: name.clone(),
                graph,
                title,
                summary,
            });
            pages.insert(name, page);
        }
        ensure!(
            !index.is_empty(),
            "ess generated no domain pages for {system}"
        );
        ensure!(
            index.len() == data.len(),
            "ess generated {} domain pages for {} domains of {system}",
            index.len(),
            data.len()
        );
        Ok((pages, index))
    })();
    let _ = fs::remove_dir_all(&scratch);
    let (pages, index) = result?;
    Ok((data, pages, index))
}

/// Run `ess` over every system of [`ESS_SYSTEMS`] and build the ESS reference and its graphs.
fn ess_outputs(root: &Path, ess: &Path) -> Result<Outputs> {
    let mut data = Pages::new();
    let mut pages = Pages::new();
    let mut index = Vec::new();
    for system in ESS_SYSTEMS {
        let (graphs, domain_pages, entries) = ess_system(root, system, ess)?;
        for (name, content) in graphs.into_iter().chain(domain_pages) {
            let target = if name.ends_with(".json") {
                &mut data
            } else {
                &mut pages
            };
            ensure!(
                target.insert(name.clone(), content).is_none(),
                "two ESS systems generate {name}"
            );
        }
        index.extend(entries);
    }
    pages.insert("index.mdx".to_owned(), index_page(&index));
    Ok(Outputs::from([(ESS_REFERENCE, pages), (ESS_DATA, data)]))
}

/// Generated pages that stand alone, keyed by path relative to the repository root.
fn single_pages(root: &Path) -> Result<Pages> {
    Ok(Pages::from([
        (cli::PAGE.to_owned(), cli::page()),
        (crates::PAGE.to_owned(), crates::page(root)?),
    ]))
}

/// Every difference between the expected files and the files in `dir`.
fn drift(expected: &Pages, dir: &Path) -> Result<Vec<String>> {
    let mut actual = Pages::new();
    if dir.exists() {
        for entry in fs::read_dir(dir)? {
            let entry = entry?;
            let name = entry.file_name().to_string_lossy().into_owned();
            actual.insert(name, fs::read_to_string(entry.path())?);
        }
    }
    let mut problems = Vec::new();
    for (name, content) in expected {
        match actual.get(name) {
            None => problems.push(format!("missing {name}")),
            Some(found) if found != content => problems.push(format!("stale or edited {name}")),
            Some(_) => {}
        }
    }
    for name in actual.keys().filter(|name| !expected.contains_key(*name)) {
        problems.push(format!("not generated {name}"));
    }
    Ok(problems)
}

fn main() -> Result<()> {
    match Cli::parse().command {
        Action::Generate { check, root, ess } => {
            let outputs = ess_outputs(&root, &ess)?;
            for (relative, files) in &outputs {
                let dir = root.join(relative);
                if check {
                    let problems = drift(files, &dir)?;
                    if !problems.is_empty() {
                        bail!(
                            "{relative} has drifted ({}); run `task docs-generate`",
                            problems.join(", ")
                        );
                    }
                    println!("{relative}: {} generated files current", files.len());
                    if relative == &ESS_REFERENCE {
                        let raw = raw_admonitions(&root.join(DOCS))?;
                        if !raw.is_empty() {
                            bail!(
                                "raw admonition titles (write `:::kind[Title]`): {}",
                                raw.join(", ")
                            );
                        }
                        println!("{DOCS}: no raw admonition titles");
                    }
                } else {
                    if dir.exists() {
                        fs::remove_dir_all(&dir)?;
                    }
                    fs::create_dir_all(&dir)?;
                    for (name, content) in files {
                        fs::write(dir.join(name), content)?;
                    }
                    println!("{relative}: wrote {} files", files.len());
                }
            }
            for (relative, content) in single_pages(&root)? {
                let path = root.join(&relative);
                if check {
                    match fs::read_to_string(&path) {
                        Ok(found) if found == content => println!("{relative}: current"),
                        Ok(_) => bail!("{relative} is stale or edited; run `task docs-generate`"),
                        Err(_) => bail!("{relative} is missing; run `task docs-generate`"),
                    }
                } else {
                    fs::write(&path, content)?;
                    println!("{relative}: written");
                }
            }
        }
        Action::Provenance { site, commit } => {
            write_provenance(&site, &commit)?;
            println!("{}: bound to {commit}", site.display());
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    const SAMPLE: &str = "<!--\ngenerated from loom v1\ndo not edit: regenerate with `ess generate`\n-->\n\n# Run\n\nOne model session.\nArguments for one action.\n\n`loom.run` is one of loom's bounded contexts. [Back to the index](../index.md).\n\nDo not edit this file; regenerate it with `ess generate`.\n";

    fn scratch(name: &str) -> PathBuf {
        let dir =
            std::env::temp_dir().join(format!("loom-docs-test-{name}-{}", std::process::id()));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();
        dir
    }

    #[test]
    fn domain_pages_carry_the_header_and_no_ess_banner() {
        let (title, summary, page) = domain_page(SAMPLE).unwrap();
        assert_eq!(title, "Run");
        assert_eq!(summary, "One model session. Arguments for one action.");
        assert!(
            page.starts_with("---\n# generated by loom-docs, do not edit\ntitle: \"Run domain\"\n")
        );
        assert!(page.contains("custom_edit_url: null\n---\n"));
        assert!(page.contains(&format!("---\n\n{HEADER}\n\n# Run\n")));
        assert!(!page.contains("generated from loom v1"));
        assert!(page.contains("[All domains](./index.mdx)"));
        assert!(page.contains("`task docs-generate`"));
    }

    #[test]
    fn links_out_of_the_domain_set_are_refused() {
        let leaking = SAMPLE.replace("One model session.", "See [crossings](../crossings.md).");
        assert!(domain_page(&leaking).is_err());
        assert!(domain_page("# Run\n\nNo banner.\n").is_err());
    }

    #[test]
    fn index_renders_one_graph_per_domain_under_the_header() {
        let page = index_page(&[DomainEntry {
            page: "loom-run.md".into(),
            graph: "loom-run.domain-graph.json".into(),
            title: "Run".into(),
            summary: "One session.".into(),
        }]);
        assert!(page.contains(MDX_HEADER));
        assert!(!page.contains("<!--"));
        assert!(
            page.contains("import domainGraph0 from '@site/data/ess/loom-run.domain-graph.json';")
        );
        assert!(page.contains("<DomainGraph data={domainGraph0} title=\"Run\" />"));
        assert!(page.contains("[Read the Run domain in full](./loom-run.md)"));
    }

    #[test]
    fn provenance_names_the_commit_and_refuses_a_bad_one() {
        let commit = "e86f43d90b637fc2c1790f77d59efff2eb852386";
        let manifest = site_manifest(commit).unwrap();
        assert!(manifest.contains(&format!("\"commit\": \"{commit}\"")));
        assert!(manifest.contains("\"schema\": \"b10x-project-site/v1\""));
        assert!(manifest.contains("\"baseUrl\": \"/loom/\""));
        assert!(site_manifest("e86f43d").is_err());
        assert!(site_manifest(&"0".repeat(40)).is_err());
        assert!(site_manifest(&format!("{}\"", &commit[..39])).is_err());

        let site = scratch("provenance");
        assert!(write_provenance(&site, commit).is_err());
        fs::write(site.join("index.html"), "").unwrap();
        write_provenance(&site, commit).unwrap();
        let written = fs::read_to_string(site.join(".well-known/b10x-site.json")).unwrap();
        assert_eq!(written, manifest);
        fs::remove_dir_all(site).unwrap();
    }

    #[test]
    fn raw_admonition_titles_are_found_and_bracketed_ones_pass() {
        for raw in [
            ":::caution Planned",
            ":::note  These thresholds",
            ":::info Decided design",
        ] {
            assert!(is_raw_admonition(raw), "{raw}");
        }
        for fine in [
            ":::caution[Planned]",
            ":::",
            ":::note",
            ":::note ",
            "::: note Title",
            ":::Note Title",
            " :::note Title",
        ] {
            assert!(!is_raw_admonition(fine), "{fine}");
        }

        let dir = scratch("admonitions");
        fs::create_dir_all(dir.join("concepts")).unwrap();
        fs::write(dir.join("index.md"), ":::caution[Bootstrap]\nok\n:::\n").unwrap();
        fs::write(
            dir.join("concepts/a.mdx"),
            "text\n:::caution Planned\n:::\n",
        )
        .unwrap();
        fs::write(dir.join("notes.txt"), ":::caution Planned\n").unwrap();
        let found = raw_admonitions(&dir).unwrap();
        assert_eq!(found.len(), 1);
        assert!(found[0].ends_with("concepts/a.mdx:2"), "{found:?}");
        fs::remove_dir_all(dir).unwrap();
    }

    #[test]
    fn drift_names_missing_edited_and_stray_pages() {
        let dir = scratch("drift");
        let mut expected = Pages::new();
        expected.insert("a.md".into(), "A\n".into());
        expected.insert("b.md".into(), "B\n".into());
        assert_eq!(
            drift(&expected, &dir).unwrap(),
            ["missing a.md", "missing b.md"]
        );
        fs::write(dir.join("a.md"), "A\n").unwrap();
        fs::write(dir.join("b.md"), "B, edited by hand\n").unwrap();
        fs::write(dir.join("c.md"), "C\n").unwrap();
        assert_eq!(
            drift(&expected, &dir).unwrap(),
            ["stale or edited b.md", "not generated c.md"]
        );
        fs::write(dir.join("b.md"), "B\n").unwrap();
        fs::remove_file(dir.join("c.md")).unwrap();
        assert!(drift(&expected, &dir).unwrap().is_empty());
        fs::remove_dir_all(dir).unwrap();
    }
}
