#![forbid(unsafe_code)]
//! Generates the derivable part of the documentation site as Markdown under
//! `website/docs/reference/`, checks it for drift, and binds a built site to its source commit.
//! The site build itself is Docusaurus.
//!
//! Loom has no command line of its own (`b10x-loom` is a library), so the only generated
//! reference is the ESS domain reference, produced by `ess generate --kind docs`.
use std::{
    collections::BTreeMap,
    fs,
    path::{Path, PathBuf},
    process::Command,
};

use anyhow::{Context, Result, bail, ensure};
use clap::{Parser, Subcommand};

/// The line every generated page carries directly after its front matter.
const HEADER: &str = "<!-- generated by loom-docs, do not edit -->";
/// Where the ESS reference lands, relative to the repository root.
const ESS_REFERENCE: &str = "website/docs/reference/ess";

#[derive(Parser)]
#[command(about = "Generate and check the derived pages of the Loom documentation site")]
struct Cli {
    #[command(subcommand)]
    command: Action,
}

#[derive(Subcommand)]
enum Action {
    /// Regenerate website/docs/reference/ from the repository, or check it for drift.
    Generate {
        /// Write nothing; fail when a generated page is missing, stale or hand-edited.
        #[arg(long)]
        check: bool,
        /// Repository root.
        #[arg(long, default_value = ".")]
        root: PathBuf,
        /// The `ess` executable.
        #[arg(long, default_value = "ess")]
        ess: PathBuf,
    },
    /// Bind a built site to its source commit: write `.well-known/b10x-site.json` into it.
    Provenance {
        /// The built site, `website/build`.
        #[arg(long)]
        site: PathBuf,
        /// The full Git revision the site was built from.
        #[arg(long)]
        commit: String,
    },
}

/// The project-site publication record for one build of the `/loom/` site.
fn site_manifest(commit: &str) -> Result<String> {
    ensure!(
        commit.len() == 40
            && commit.bytes().all(|b| b.is_ascii_hexdigit())
            && commit != "0".repeat(40),
        "commit must be a nonzero full Git revision"
    );
    Ok(format!(
        "{{\n  \"baseUrl\": \"/loom/\",\n  \"commit\": \"{commit}\",\n  \"repository\": \"loom\",\n  \"schema\": \"b10x-project-site/v1\"\n}}"
    ))
}

fn write_provenance(site: &Path, commit: &str) -> Result<()> {
    let manifest = site_manifest(commit)?;
    ensure!(
        site.join("index.html").is_file(),
        "{} holds no built site",
        site.display()
    );
    fs::create_dir_all(site.join(".well-known"))?;
    fs::write(site.join(".well-known/b10x-site.json"), manifest)
        .context("writing site provenance")?;
    fs::write(site.join(".nojekyll"), "")?;
    Ok(())
}

/// Pages keyed by file name, in the order they are written.
type Pages = BTreeMap<String, String>;

/// Strip the leading HTML comment `ess generate` writes, returning the rest.
fn strip_ess_banner(page: &str) -> Result<&str> {
    let rest = page
        .strip_prefix("<!--")
        .context("ess page does not open with its provenance comment")?;
    let end = rest
        .find("-->")
        .context("ess provenance comment is not closed")?;
    Ok(rest[end + 3..].trim_start_matches('\n'))
}

/// The H1 title and the first paragraph after it.
fn title_and_summary(body: &str) -> Result<(String, String)> {
    let mut lines = body.lines();
    let title = lines
        .next()
        .and_then(|line| line.strip_prefix("# "))
        .context("ess page does not open with a level-one heading")?
        .trim()
        .to_owned();
    let summary = lines
        .skip_while(|line| line.trim().is_empty())
        .take_while(|line| !line.trim().is_empty())
        .collect::<Vec<_>>()
        .join(" ");
    ensure!(!summary.is_empty(), "ess page {title} has no summary");
    Ok((title, summary))
}

fn yaml_string(value: &str) -> String {
    format!("\"{}\"", value.replace('\\', "\\\\").replace('"', "\\\""))
}

fn front_matter(title: &str, label: &str, description: &str) -> String {
    format!(
        "---\ntitle: {}\nsidebar_label: {}\ndescription: {}\n---\n\n{HEADER}\n\n",
        yaml_string(title),
        yaml_string(label),
        yaml_string(description),
    )
}

/// One domain page of `ess generate --kind docs`, rewritten as a site page.
fn domain_page(source: &str) -> Result<(String, String, String)> {
    let body = strip_ess_banner(source)?;
    let (title, summary) = title_and_summary(body)?;
    let body = body
        .replace(
            "[Back to the index](../index.md)",
            "[All domains](./index.md)",
        )
        .replace("`ess generate`", "`task docs-generate`");
    ensure!(
        !body.contains("](../"),
        "ess page {title} links outside the generated domain pages"
    );
    let page = front_matter(
        &format!("{title} domain"),
        &title,
        &format!("ESS reference for the {title} domain, generated from the specification."),
    ) + &body;
    Ok((title, summary, page))
}

fn index_page(domains: &[(String, String, String)]) -> String {
    let mut page = front_matter(
        "ESS specification",
        "ESS specification",
        "The Loom specification, domain by domain, generated from ess/ in the repository.",
    );
    page.push_str("# ESS specification\n\n");
    page.push_str(
        "Loom is specified in ESS. These pages are generated from the repository's `ess/` \
         directory by `loom-docs`, which runs `ess generate --kind docs`. They change when the \
         specification changes, and `task check` fails if they fall behind it.\n\n",
    );
    page.push_str("| domain | what it covers |\n|---|---|\n");
    for (file, title, summary) in domains {
        let summary = summary.replace('|', "\\|");
        page.push_str(&format!("| [{title}](./{file}) | {summary} |\n"));
    }
    page
}

/// Run `ess generate --kind docs` into a scratch directory and build the reference pages.
fn ess_pages(root: &Path, ess: &Path) -> Result<Pages> {
    let scratch = std::env::temp_dir().join(format!("loom-docs-{}", std::process::id()));
    if scratch.exists() {
        fs::remove_dir_all(&scratch)?;
    }
    let result = (|| {
        let output = Command::new(ess)
            .args(["generate", "--kind", "docs", "--path"])
            .arg(root.join("ess"))
            .arg("--out")
            .arg(&scratch)
            .output()
            .with_context(|| format!("running {}", ess.display()))?;
        if !output.status.success() {
            bail!(
                "ess generate failed: {}",
                String::from_utf8_lossy(&output.stderr)
            );
        }
        let dir = scratch.join("docs/domains");
        let mut files: Vec<_> = fs::read_dir(&dir)
            .with_context(|| format!("reading {}", dir.display()))?
            .collect::<Result<_, _>>()?;
        files.sort_by_key(|entry| entry.file_name());
        let mut pages = Pages::new();
        let mut index = Vec::new();
        for entry in files {
            let name = entry.file_name().to_string_lossy().into_owned();
            if !name.ends_with(".md") {
                continue;
            }
            let (title, summary, page) = domain_page(&fs::read_to_string(entry.path())?)?;
            index.push((name.clone(), title, summary));
            pages.insert(name, page);
        }
        ensure!(!index.is_empty(), "ess generated no domain pages");
        pages.insert("index.md".to_owned(), index_page(&index));
        Ok(pages)
    })();
    let _ = fs::remove_dir_all(&scratch);
    result
}

/// Every difference between the expected pages and the Markdown files on disk.
fn drift(expected: &Pages, dir: &Path) -> Result<Vec<String>> {
    let mut actual = Pages::new();
    if dir.exists() {
        for entry in fs::read_dir(dir)? {
            let entry = entry?;
            let name = entry.file_name().to_string_lossy().into_owned();
            if name.ends_with(".md") {
                actual.insert(name, fs::read_to_string(entry.path())?);
            }
        }
    }
    let mut problems = Vec::new();
    for (name, content) in expected {
        match actual.get(name) {
            None => problems.push(format!("missing {name}")),
            Some(found) if found != content => problems.push(format!("stale or edited {name}")),
            Some(_) => {}
        }
    }
    for name in actual.keys().filter(|name| !expected.contains_key(*name)) {
        problems.push(format!("not generated {name}"));
    }
    Ok(problems)
}

fn main() -> Result<()> {
    match Cli::parse().command {
        Action::Generate { check, root, ess } => {
            let pages = ess_pages(&root, &ess)?;
            let dir = root.join(ESS_REFERENCE);
            if check {
                let problems = drift(&pages, &dir)?;
                if !problems.is_empty() {
                    bail!(
                        "{ESS_REFERENCE} has drifted ({}); run `task docs-generate`",
                        problems.join(", ")
                    );
                }
                println!("{ESS_REFERENCE}: {} generated pages current", pages.len());
            } else {
                if dir.exists() {
                    fs::remove_dir_all(&dir)?;
                }
                fs::create_dir_all(&dir)?;
                for (name, content) in &pages {
                    fs::write(dir.join(name), content)?;
                }
                println!("{ESS_REFERENCE}: wrote {} pages", pages.len());
            }
        }
        Action::Provenance { site, commit } => {
            write_provenance(&site, &commit)?;
            println!("{}: bound to {commit}", site.display());
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    const SAMPLE: &str = "<!--\ngenerated from loom v1\ndo not edit: regenerate with `ess generate`\n-->\n\n# Run\n\nOne model session.\nArguments for one action.\n\n`loom.run` is one of loom's bounded contexts. [Back to the index](../index.md).\n\nDo not edit this file; regenerate it with `ess generate`.\n";

    fn scratch(name: &str) -> PathBuf {
        let dir =
            std::env::temp_dir().join(format!("loom-docs-test-{name}-{}", std::process::id()));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();
        dir
    }

    #[test]
    fn domain_pages_carry_the_header_and_no_ess_banner() {
        let (title, summary, page) = domain_page(SAMPLE).unwrap();
        assert_eq!(title, "Run");
        assert_eq!(summary, "One model session. Arguments for one action.");
        assert!(page.starts_with("---\ntitle: \"Run domain\"\n"));
        assert!(page.contains(&format!("---\n\n{HEADER}\n\n# Run\n")));
        assert!(!page.contains("generated from loom v1"));
        assert!(page.contains("[All domains](./index.md)"));
        assert!(page.contains("`task docs-generate`"));
    }

    #[test]
    fn links_out_of_the_domain_set_are_refused() {
        let leaking = SAMPLE.replace("One model session.", "See [crossings](../crossings.md).");
        assert!(domain_page(&leaking).is_err());
        assert!(domain_page("# Run\n\nNo banner.\n").is_err());
    }

    #[test]
    fn index_lists_every_domain_under_the_header() {
        let page = index_page(&[("loom-run.md".into(), "Run".into(), "One session.".into())]);
        assert!(page.contains(HEADER));
        assert!(page.contains("| [Run](./loom-run.md) | One session. |"));
    }

    #[test]
    fn provenance_names_the_commit_and_refuses_a_bad_one() {
        let commit = "e86f43d90b637fc2c1790f77d59efff2eb852386";
        let manifest = site_manifest(commit).unwrap();
        assert!(manifest.contains(&format!("\"commit\": \"{commit}\"")));
        assert!(manifest.contains("\"schema\": \"b10x-project-site/v1\""));
        assert!(manifest.contains("\"baseUrl\": \"/loom/\""));
        assert!(site_manifest("e86f43d").is_err());
        assert!(site_manifest(&"0".repeat(40)).is_err());
        assert!(site_manifest(&format!("{}\"", &commit[..39])).is_err());

        let site = scratch("provenance");
        assert!(write_provenance(&site, commit).is_err());
        fs::write(site.join("index.html"), "").unwrap();
        write_provenance(&site, commit).unwrap();
        let written = fs::read_to_string(site.join(".well-known/b10x-site.json")).unwrap();
        assert_eq!(written, manifest);
        fs::remove_dir_all(site).unwrap();
    }

    #[test]
    fn drift_names_missing_edited_and_stray_pages() {
        let dir = scratch("drift");
        let mut expected = Pages::new();
        expected.insert("a.md".into(), "A\n".into());
        expected.insert("b.md".into(), "B\n".into());
        assert_eq!(
            drift(&expected, &dir).unwrap(),
            ["missing a.md", "missing b.md"]
        );
        fs::write(dir.join("a.md"), "A\n").unwrap();
        fs::write(dir.join("b.md"), "B, edited by hand\n").unwrap();
        fs::write(dir.join("c.md"), "C\n").unwrap();
        assert_eq!(
            drift(&expected, &dir).unwrap(),
            ["stale or edited b.md", "not generated c.md"]
        );
        fs::write(dir.join("b.md"), "B\n").unwrap();
        fs::remove_file(dir.join("c.md")).unwrap();
        assert!(drift(&expected, &dir).unwrap().is_empty());
        fs::remove_dir_all(dir).unwrap();
    }
}
