#![forbid(unsafe_code)]

//! Repository checks for Commission.
//!
//! The responsibility model is generated by `ess generate synthesize` into
//! `generated/rust/commission/`. `generate` rewrites that tree from `ess/`; `drift` fails when the
//! committed tree differs from a fresh synthesis or `b10x-commission` does not take its model from
//! it; `no-hand-model` fails when `crates/commission/src` defines, or renames something to, a type
//! the generated crate declares.

use clap::{Parser, Subcommand};
use std::collections::BTreeSet;
use std::fs;
use std::io;
use std::path::{Path, PathBuf};
use std::process::{Command as Process, ExitCode};
use std::time::{SystemTime, UNIX_EPOCH};
use syn::ext::IdentExt;
use syn::visit::Visit;

/// Where the generated crate is committed, relative to the repository root.
const GENERATED: &str = "generated/rust/commission";
/// The generated crate's package name.
const GENERATED_PACKAGE: &str = "commission";
/// The specification, relative to the repository root.
const SPECIFICATION: &str = "ess";
/// The sources that must not define a model type, relative to the repository root: the crate and
/// the testkit whose fakes stand in for its ports.
const HAND_MODEL_SOURCES: [&str; 2] = ["crates/commission/src", "crates/commission-testkit/src"];
/// The manifest that must take the model from the generated crate, relative to the root.
const COMMISSION_MANIFEST: &str = "crates/commission/Cargo.toml";
/// The crate root that must re-export the generated crate, relative to the root.
const COMMISSION_LIB: &str = "crates/commission/src/lib.rs";
/// The name `b10x-commission` re-exports the generated crate under.
const MODEL_REEXPORT: &str = "model";
/// Synthesis state: per-run anchor id, inode and absolute root. Never compared, never committed.
const ESS_OUTPUT: &str = ".ess-output";

#[derive(Debug, Parser)]
#[command(name = "commission-xtask", about = "Repository checks for Commission")]
struct Cli {
    /// Repository root. Defaults to the nearest ancestor of the current directory holding
    /// `ess/ess-inputs.yaml`.
    #[arg(long, global = true)]
    root: Option<PathBuf>,
    #[command(subcommand)]
    command: Command,
}

#[derive(Debug, Subcommand)]
enum Command {
    /// Rewrite `generated/rust/commission/` from a fresh synthesis of `ess/`.
    Generate {
        #[command(flatten)]
        synthesis: Synthesis,
    },
    /// Fail when `generated/rust/commission/` differs from a fresh synthesis of `ess/`, or when
    /// `b10x-commission` does not take its model from that tree.
    Drift {
        #[command(flatten)]
        synthesis: Synthesis,
        /// The committed tree to compare. Defaults to `<root>/generated/rust/commission`.
        #[arg(long)]
        generated: Option<PathBuf>,
    },
    /// Fail when a source file of `b10x-commission` or `b10x-commission-testkit` defines, or
    /// renames something to, a type the generated crate declares.
    NoHandModel {
        /// A source directory to scan; repeat for more. Defaults to `<root>/crates/commission/src`
        /// and `<root>/crates/commission-testkit/src`.
        #[arg(long)]
        src: Vec<PathBuf>,
        /// The generated crate whose type names are reserved. Defaults to
        /// `<root>/generated/rust/commission`.
        #[arg(long)]
        generated: Option<PathBuf>,
    },
}

#[derive(Debug, clap::Args)]
struct Synthesis {
    /// Directory for the temporary regeneration tree. Defaults to
    /// `$CARGO_TARGET_DIR/commission-xtask`, or `<root>/target/commission-xtask`.
    #[arg(long)]
    scratch: Option<PathBuf>,
    /// The `ess` executable.
    #[arg(long, default_value = "ess")]
    ess: PathBuf,
}

fn main() -> ExitCode {
    let cli = Cli::parse();
    match run(cli) {
        Ok(()) => ExitCode::SUCCESS,
        Err(message) => {
            eprintln!("{message}");
            ExitCode::FAILURE
        }
    }
}

fn run(cli: Cli) -> Result<(), String> {
    let root = match cli.root {
        Some(root) => root,
        None => find_root()?,
    };
    match cli.command {
        Command::Generate { synthesis } => generate(&root, &synthesis),
        Command::Drift {
            synthesis,
            generated,
        } => drift(
            &root,
            &synthesis,
            &generated.unwrap_or_else(|| root.join(GENERATED)),
        ),
        Command::NoHandModel { src, generated } => no_hand_model(
            &if src.is_empty() {
                HAND_MODEL_SOURCES
                    .iter()
                    .map(|dir| root.join(dir))
                    .collect()
            } else {
                src
            },
            &generated.unwrap_or_else(|| root.join(GENERATED)),
        ),
    }
}

fn find_root() -> Result<PathBuf, String> {
    let cwd = std::env::current_dir().map_err(|e| format!("current directory: {e}"))?;
    cwd.ancestors()
        .find(|dir| dir.join(SPECIFICATION).join("ess-inputs.yaml").is_file())
        .map(Path::to_path_buf)
        .ok_or_else(|| {
            format!(
                "no ancestor of {} holds {SPECIFICATION}/ess-inputs.yaml; pass --root",
                cwd.display()
            )
        })
}

/// Synthesizes into scratch, stages the complete tree beside the target, then swaps it in by
/// rename. The committed tree is never removed before its replacement is complete.
fn generate(root: &Path, synthesis: &Synthesis) -> Result<(), String> {
    let fresh = Regeneration::synthesize(root, synthesis)?;
    let target = root.join(GENERATED);
    let parent = target
        .parent()
        .ok_or_else(|| format!("{} has no parent", target.display()))?;
    fs::create_dir_all(parent).map_err(|e| format!("create {}: {e}", parent.display()))?;

    let staging = Staging::new(parent.join(format!(".commission.staging-{}", std::process::id())))?;
    for relative in tree_files(&fresh.dir)? {
        let to = staging.dir.join(&relative);
        if let Some(dir) = to.parent() {
            fs::create_dir_all(dir).map_err(|e| format!("create {}: {e}", dir.display()))?;
        }
        fs::copy(fresh.dir.join(&relative), &to)
            .map_err(|e| format!("write {}: {e}", to.display()))?;
    }

    if !target.exists() {
        fs::rename(&staging.dir, &target)
            .map_err(|e| format!("move the new tree to {}: {e}", target.display()))?;
    } else {
        let old = parent.join(format!(".commission.old-{}", std::process::id()));
        if old.exists() {
            fs::remove_dir_all(&old).map_err(|e| format!("remove {}: {e}", old.display()))?;
        }
        fs::rename(&target, &old).map_err(|e| format!("move {} aside: {e}", target.display()))?;
        if let Err(error) = fs::rename(&staging.dir, &target) {
            let restored = fs::rename(&old, &target);
            return Err(format!(
                "move the new tree to {}: {error}; previous tree {}",
                target.display(),
                match restored {
                    Ok(()) => "restored".to_string(),
                    Err(e) => format!("left at {}: {e}", old.display()),
                }
            ));
        }
        fs::remove_dir_all(&old).map_err(|e| {
            format!(
                "{GENERATED} regenerated, but the previous tree at {} could not be removed: {e}",
                old.display()
            )
        })?;
    }
    println!("{GENERATED}: regenerated from {SPECIFICATION}/");
    Ok(())
}

/// A staging tree beside the target, removed when dropped unless it was moved into place.
struct Staging {
    dir: PathBuf,
}

impl Staging {
    fn new(dir: PathBuf) -> Result<Self, String> {
        if dir.exists() {
            fs::remove_dir_all(&dir).map_err(|e| format!("remove {}: {e}", dir.display()))?;
        }
        Ok(Self { dir })
    }
}

impl Drop for Staging {
    fn drop(&mut self) {
        if self.dir.exists() {
            let _ = fs::remove_dir_all(&self.dir);
        }
    }
}

fn drift(root: &Path, synthesis: &Synthesis, committed: &Path) -> Result<(), String> {
    let mut problems = binding_problems(root)?;

    let fresh = Regeneration::synthesize(root, synthesis)?;
    let differences = compare_trees(&fresh.dir, committed)?;
    if !differences.is_empty() {
        let mut message = format!(
            "{} drifted from a fresh synthesis of {SPECIFICATION}/ (run `task generate`):",
            committed.display()
        );
        for difference in &differences {
            message.push_str("\n  ");
            message.push_str(&difference.to_string());
        }
        problems.push(message);
    }

    if problems.is_empty() {
        println!("{}: no drift from {SPECIFICATION}/", committed.display());
        Ok(())
    } else {
        Err(problems.join("\n"))
    }
}

/// What ties `b10x-commission` to the generated tree: every dependency that names the
/// `commission` package, or is called `commission`, is a path dependency on
/// `generated/rust/commission`, and the crate root re-exports that dependency as `model`.
fn binding_problems(root: &Path) -> Result<Vec<String>, String> {
    let mut problems = Vec::new();
    let generated = root
        .join(GENERATED)
        .canonicalize()
        .map_err(|e| format!("{GENERATED}: {e}"))?;

    let manifest_path = root.join(COMMISSION_MANIFEST);
    let manifest_dir = manifest_path
        .parent()
        .ok_or_else(|| format!("{COMMISSION_MANIFEST} has no parent"))?;
    let manifest: toml::Table = fs::read_to_string(&manifest_path)
        .map_err(|e| format!("read {}: {e}", manifest_path.display()))?
        .parse()
        .map_err(|e| format!("parse {}: {e}", manifest_path.display()))?;

    let mut tables: Vec<(String, &toml::Table)> = Vec::new();
    for kind in ["dependencies", "dev-dependencies", "build-dependencies"] {
        if let Some(table) = manifest.get(kind).and_then(toml::Value::as_table) {
            tables.push((kind.to_string(), table));
        }
    }
    if let Some(targets) = manifest.get("target").and_then(toml::Value::as_table) {
        for (cfg, target) in targets {
            for kind in ["dependencies", "dev-dependencies", "build-dependencies"] {
                if let Some(table) = target.get(kind).and_then(toml::Value::as_table) {
                    tables.push((format!("target.{cfg}.{kind}"), table));
                }
            }
        }
    }

    let mut bound = false;
    for (section, table) in tables {
        for (key, value) in table {
            let package = value
                .get("package")
                .and_then(toml::Value::as_str)
                .unwrap_or(key);
            if key != GENERATED_PACKAGE && package != GENERATED_PACKAGE {
                continue;
            }
            let at = format!("{COMMISSION_MANIFEST} [{section}] `{key}`");
            if package != GENERATED_PACKAGE {
                problems.push(format!(
                    "{at}: names package `{package}`, not the generated `{GENERATED_PACKAGE}`"
                ));
                continue;
            }
            let Some(path) = value.get("path").and_then(toml::Value::as_str) else {
                problems.push(format!("{at}: is not a path dependency on {GENERATED}"));
                continue;
            };
            match manifest_dir.join(path).canonicalize() {
                Ok(resolved) if resolved == generated => {
                    if key == GENERATED_PACKAGE && section == "dependencies" {
                        bound = true;
                    }
                }
                Ok(resolved) => problems.push(format!(
                    "{at}: path `{path}` resolves to {}, not {GENERATED}",
                    resolved.display()
                )),
                Err(e) => problems.push(format!("{at}: path `{path}` does not resolve: {e}")),
            }
        }
    }
    if !bound {
        problems.push(format!(
            "{COMMISSION_MANIFEST}: no [dependencies] `{GENERATED_PACKAGE}` on {GENERATED}"
        ));
    }

    let lib_path = root.join(COMMISSION_LIB);
    let lib =
        fs::read_to_string(&lib_path).map_err(|e| format!("read {}: {e}", lib_path.display()))?;
    let file = syn::parse_file(&lib).map_err(|e| {
        format!(
            "{}:{}: not readable as Rust: {e}",
            lib_path.display(),
            e.span().start().line
        )
    })?;
    let mut reexported = false;
    for item in &file.items {
        let (name, line, is_reexport) = match item {
            syn::Item::Use(item) => match &item.tree {
                syn::UseTree::Rename(rename) => (
                    rename.rename.unraw(),
                    rename.rename.span().start().line,
                    matches!(item.vis, syn::Visibility::Public(_))
                        && rename.ident.unraw() == GENERATED_PACKAGE,
                ),
                _ => continue,
            },
            syn::Item::Mod(item) => (item.ident.unraw(), item.ident.span().start().line, false),
            _ => continue,
        };
        if name != MODEL_REEXPORT {
            continue;
        }
        if is_reexport {
            reexported = true;
        } else {
            problems.push(format!(
                "{COMMISSION_LIB}:{line}: `{MODEL_REEXPORT}` is not the generated crate; \
                 expected `pub use {GENERATED_PACKAGE} as {MODEL_REEXPORT};`"
            ));
        }
    }
    if !reexported {
        problems.push(format!(
            "{COMMISSION_LIB}: does not re-export the generated crate: expected \
             `pub use {GENERATED_PACKAGE} as {MODEL_REEXPORT};`"
        ));
    }
    Ok(problems)
}

/// A fresh synthesis in its own directory under the scratch root, removed when dropped.
struct Regeneration {
    dir: PathBuf,
}

impl Regeneration {
    fn synthesize(root: &Path, synthesis: &Synthesis) -> Result<Self, String> {
        let scratch = match &synthesis.scratch {
            Some(dir) => dir.clone(),
            None => default_scratch(root),
        };
        fs::create_dir_all(&scratch)
            .map_err(|e| format!("create scratch {}: {e}", scratch.display()))?;
        let nanos = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .map(|d| d.as_nanos())
            .unwrap_or_default();
        let regeneration = Self {
            dir: scratch.join(format!("regen-{}-{nanos}", std::process::id())),
        };
        let output = Process::new(&synthesis.ess)
            .args(["generate", "synthesize", "--path"])
            .arg(root.join(SPECIFICATION))
            .args(["--target", "rust", "--layout", "crate", "--out"])
            .arg(&regeneration.dir)
            .output()
            .map_err(|e| format!("run {}: {e}", synthesis.ess.display()))?;
        if !output.status.success() {
            return Err(format!(
                "`{} generate synthesize` failed ({}):\n{}{}",
                synthesis.ess.display(),
                output.status,
                String::from_utf8_lossy(&output.stdout),
                String::from_utf8_lossy(&output.stderr)
            ));
        }
        Ok(regeneration)
    }
}

impl Drop for Regeneration {
    fn drop(&mut self) {
        if self.dir.exists() {
            let _ = fs::remove_dir_all(&self.dir);
        }
    }
}

fn default_scratch(root: &Path) -> PathBuf {
    std::env::var_os("CARGO_TARGET_DIR")
        .map(PathBuf::from)
        .unwrap_or_else(|| root.join("target"))
        .join("commission-xtask")
}

#[derive(Debug, PartialEq, Eq)]
enum Difference {
    /// Synthesis writes it; the committed tree lacks it.
    Missing(String),
    /// The committed tree has it; synthesis does not write it.
    Unexpected(String),
    /// Both have it, with different bytes.
    Changed(String),
}

impl std::fmt::Display for Difference {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Missing(path) => write!(f, "{path}: missing from the committed tree"),
            Self::Unexpected(path) => write!(f, "{path}: not produced by synthesis"),
            Self::Changed(path) => write!(f, "{path}: differs from synthesis"),
        }
    }
}

/// Compares two trees file by file, ignoring `.ess-output/` at the top of either.
fn compare_trees(expected: &Path, actual: &Path) -> Result<Vec<Difference>, String> {
    let expected_files = tree_files(expected)?;
    let actual_files = if actual.is_dir() {
        tree_files(actual)?
    } else {
        BTreeSet::new()
    };
    let mut differences = Vec::new();
    for path in expected_files.union(&actual_files) {
        let name = path.to_string_lossy().into_owned();
        match (expected_files.contains(path), actual_files.contains(path)) {
            (true, false) => differences.push(Difference::Missing(name)),
            (false, true) => differences.push(Difference::Unexpected(name)),
            _ => {
                let want = read(&expected.join(path))?;
                let have = read(&actual.join(path))?;
                if want != have {
                    differences.push(Difference::Changed(name));
                }
            }
        }
    }
    Ok(differences)
}

fn read(path: &Path) -> Result<Vec<u8>, String> {
    fs::read(path).map_err(|e| format!("read {}: {e}", path.display()))
}

/// Every file under `root`, relative to it, leaving out `.ess-output/`.
fn tree_files(root: &Path) -> Result<BTreeSet<PathBuf>, String> {
    let mut files = BTreeSet::new();
    walk(root, Path::new(""), &mut files)
        .map_err(|e| format!("read tree {}: {e}", root.display()))?;
    Ok(files)
}

fn walk(root: &Path, relative: &Path, files: &mut BTreeSet<PathBuf>) -> io::Result<()> {
    for entry in fs::read_dir(root.join(relative))? {
        let entry = entry?;
        let path = relative.join(entry.file_name());
        if path == Path::new(ESS_OUTPUT) {
            continue;
        }
        if entry.file_type()?.is_dir() {
            walk(root, &path, files)?;
        } else {
            files.insert(path);
        }
    }
    Ok(())
}

/// The `.rs` files under `dir`, each with its path and text.
fn rust_sources(dir: &Path) -> Result<Vec<(PathBuf, String)>, String> {
    let mut files = BTreeSet::new();
    walk(dir, Path::new(""), &mut files)
        .map_err(|e| format!("read sources {}: {e}", dir.display()))?;
    files
        .into_iter()
        .filter(|p| p.extension().is_some_and(|ext| ext == "rs"))
        .map(|relative| {
            let path = dir.join(relative);
            fs::read_to_string(&path)
                .map(|text| (path.clone(), text))
                .map_err(|e| format!("read {}: {e}", path.display()))
        })
        .collect()
}

fn parse(path: &Path, text: &str) -> Result<syn::File, String> {
    syn::parse_file(text).map_err(|e| {
        format!(
            "{}:{}: not readable as Rust, so it cannot be checked: {e}",
            path.display(),
            e.span().start().line
        )
    })
}

/// The type names the generated crate declares at the top of each of its files, and the trait
/// names it declares in the inline modules below them (`obligations::StartRunBehavior`,
/// `run_state::Marker`), descending only into `pub` modules: a private module such as
/// `run_state::sealed` exports nothing, so its `Sealed` names no model type. A nested struct is a
/// state marker (`run_state::Running`) whose name is a state, not a model type, so it is not
/// reserved.
fn generated_type_names(generated: &Path) -> Result<BTreeSet<String>, String> {
    /// The module's items, when it is `pub` and inline.
    fn public_items(item: &syn::ItemMod) -> Option<&[syn::Item]> {
        match (&item.vis, &item.content) {
            (syn::Visibility::Public(_), Some((_, items))) => Some(items),
            _ => None,
        }
    }

    fn nested_traits(items: &[syn::Item], names: &mut BTreeSet<String>) {
        for item in items {
            match item {
                syn::Item::Trait(item) => {
                    names.insert(item.ident.unraw().to_string());
                }
                syn::Item::TraitAlias(item) => {
                    names.insert(item.ident.unraw().to_string());
                }
                syn::Item::Mod(item) => {
                    if let Some(items) = public_items(item) {
                        nested_traits(items, names);
                    }
                }
                _ => {}
            }
        }
    }

    let mut names = BTreeSet::new();
    for (path, text) in rust_sources(&generated.join("src"))? {
        for item in parse(&path, &text)?.items {
            let ident = match item {
                syn::Item::Struct(item) => item.ident,
                syn::Item::Enum(item) => item.ident,
                syn::Item::Union(item) => item.ident,
                syn::Item::Type(item) => item.ident,
                syn::Item::Trait(item) => item.ident,
                syn::Item::TraitAlias(item) => item.ident,
                syn::Item::Mod(item) => {
                    if let Some(items) = public_items(&item) {
                        nested_traits(items, &mut names);
                    }
                    continue;
                }
                _ => continue,
            };
            names.insert(ident.unraw().to_string());
        }
    }
    if names.is_empty() {
        return Err(format!(
            "{}: declares no type, so there is nothing to check against; run `task generate`",
            generated.display()
        ));
    }
    Ok(names)
}

fn no_hand_model(srcs: &[PathBuf], generated: &Path) -> Result<(), String> {
    let names = generated_type_names(generated)?;
    let mut findings = Vec::new();
    let mut sources = Vec::new();
    for src in srcs {
        sources.extend(rust_sources(src)?);
    }
    for (path, text) in sources {
        for found in hand_model_items(&parse(&path, &text)?, &names) {
            let problem = match found.problem {
                Problem::ModelType => format!(
                    "is a hand-written model type; take it from the generated crate \
                     (`b10x_commission::{MODEL_REEXPORT}`)"
                ),
                Problem::Include => "brings in source this check cannot read; write the items \
                                     in a scanned file instead"
                    .to_string(),
                Problem::PathAttribute => "loads a module file this check does not follow; \
                                           remove the attribute so the module lies under a \
                                           scanned directory"
                    .to_string(),
            };
            findings.push(format!(
                "{}:{}: `{}` {problem}",
                path.display(),
                found.line,
                found.item
            ));
        }
    }
    if findings.is_empty() {
        for src in srcs {
            println!(
                "{}: no hand-written model type ({} generated type names checked)",
                src.display(),
                names.len()
            );
        }
        Ok(())
    } else {
        Err(findings.join("\n"))
    }
}

#[derive(Debug, PartialEq, Eq)]
struct Found {
    line: usize,
    item: String,
    problem: Problem,
}

/// Why a finding is refused.
#[derive(Debug, PartialEq, Eq)]
enum Problem {
    /// A definition of, or a rename to, a generated type's name.
    ModelType,
    /// `include!`, whose source the check cannot read.
    Include,
    /// A `#[path]` module, whose file the check does not follow.
    PathAttribute,
}

/// The keywords that open a type definition, in source or in a macro's tokens.
const TYPE_KEYWORDS: [&str; 5] = ["struct", "enum", "type", "union", "trait"];

/// Every item definition named after a generated type, and every `use … as <name>` that gives
/// something else a generated type's name, anywhere in the file. Raw identifiers count as the
/// identifier; literals and comments are not code and are not read.
///
/// Macros are not expanded. Instead the tokens of every macro — `macro_rules!` bodies and every
/// invocation, in any position — are read for a type keyword directly followed by a generated
/// name, and refused as a definition. `include!` is refused outright, and so is a module carrying a
/// `#[path]` attribute (directly or through `cfg_attr`): both bring in source from a file the scan
/// does not read.
fn hand_model_items(file: &syn::File, names: &BTreeSet<String>) -> Vec<Found> {
    struct Scan<'a> {
        names: &'a BTreeSet<String>,
        found: Vec<Found>,
    }

    impl Scan<'_> {
        fn definition(&mut self, keyword: &str, ident: &syn::Ident) {
            let name = ident.unraw().to_string();
            if self.names.contains(&name) {
                self.found.push(Found {
                    line: ident.span().start().line,
                    item: format!("{keyword} {name}"),
                    problem: Problem::ModelType,
                });
            }
        }

        /// A type keyword directly followed by a generated name, at any depth of `tokens`.
        fn macro_tokens(&mut self, tokens: proc_macro2::TokenStream) {
            let mut keyword: Option<String> = None;
            for tree in tokens {
                match tree {
                    proc_macro2::TokenTree::Ident(ident) => {
                        if let Some(keyword) = keyword.take() {
                            let name = ident.unraw().to_string();
                            if self.names.contains(&name) {
                                self.found.push(Found {
                                    line: ident.span().start().line,
                                    item: format!("{keyword} {name}"),
                                    problem: Problem::ModelType,
                                });
                            }
                        }
                        let word = ident.to_string();
                        if TYPE_KEYWORDS.contains(&word.as_str()) {
                            keyword = Some(word);
                        }
                    }
                    proc_macro2::TokenTree::Group(group) => {
                        keyword = None;
                        self.macro_tokens(group.stream());
                    }
                    _ => keyword = None,
                }
            }
        }

        /// Whether `tokens` hold `path =` at their top level, as a `cfg_attr` that sets a path does.
        fn sets_path(tokens: &proc_macro2::TokenStream) -> bool {
            let trees: Vec<_> = tokens.clone().into_iter().collect();
            trees.windows(2).any(|pair| {
                matches!(&pair[0], proc_macro2::TokenTree::Ident(ident) if ident == "path")
                    && matches!(&pair[1], proc_macro2::TokenTree::Punct(punct) if punct.as_char() == '=')
            })
        }
    }

    impl<'ast> Visit<'ast> for Scan<'_> {
        fn visit_item_struct(&mut self, item: &'ast syn::ItemStruct) {
            self.definition("struct", &item.ident);
            syn::visit::visit_item_struct(self, item);
        }
        fn visit_item_enum(&mut self, item: &'ast syn::ItemEnum) {
            self.definition("enum", &item.ident);
            syn::visit::visit_item_enum(self, item);
        }
        fn visit_item_union(&mut self, item: &'ast syn::ItemUnion) {
            self.definition("union", &item.ident);
            syn::visit::visit_item_union(self, item);
        }
        fn visit_item_type(&mut self, item: &'ast syn::ItemType) {
            self.definition("type", &item.ident);
            syn::visit::visit_item_type(self, item);
        }
        fn visit_item_trait(&mut self, item: &'ast syn::ItemTrait) {
            self.definition("trait", &item.ident);
            syn::visit::visit_item_trait(self, item);
        }
        fn visit_item_trait_alias(&mut self, item: &'ast syn::ItemTraitAlias) {
            self.definition("trait", &item.ident);
            syn::visit::visit_item_trait_alias(self, item);
        }
        fn visit_use_rename(&mut self, rename: &'ast syn::UseRename) {
            let from = rename.ident.unraw().to_string();
            let to = rename.rename.unraw().to_string();
            if from != to && self.names.contains(&to) {
                self.found.push(Found {
                    line: rename.rename.span().start().line,
                    item: format!("use {from} as {to}"),
                    problem: Problem::ModelType,
                });
            }
        }
        fn visit_macro(&mut self, mac: &'ast syn::Macro) {
            if let Some(last) = mac.path.segments.last()
                && last.ident == "include"
            {
                self.found.push(Found {
                    line: last.ident.span().start().line,
                    item: "include!".to_string(),
                    problem: Problem::Include,
                });
            }
            self.macro_tokens(mac.tokens.clone());
            syn::visit::visit_macro(self, mac);
        }
        fn visit_item_mod(&mut self, item: &'ast syn::ItemMod) {
            for attr in &item.attrs {
                let form = if attr.path().is_ident("path") {
                    Some("#[path = …]")
                } else if attr.path().is_ident("cfg_attr")
                    && matches!(&attr.meta, syn::Meta::List(list) if Self::sets_path(&list.tokens))
                {
                    Some("#[cfg_attr(…, path = …)]")
                } else {
                    None
                };
                if let Some(form) = form {
                    self.found.push(Found {
                        line: attr.pound_token.spans[0].start().line,
                        item: format!("{form} mod {}", item.ident.unraw()),
                        problem: Problem::PathAttribute,
                    });
                }
            }
            syn::visit::visit_item_mod(self, item);
        }
    }

    let mut scan = Scan {
        names,
        found: Vec::new(),
    };
    scan.visit_file(file);
    scan.found
}

#[cfg(test)]
mod tests {
    use super::*;

    fn names(list: &[&str]) -> BTreeSet<String> {
        list.iter().map(|n| n.to_string()).collect()
    }

    fn found(text: &str, list: &[&str]) -> Vec<(usize, String)> {
        let file = syn::parse_file(text).expect("parse");
        hand_model_items(&file, &names(list))
            .into_iter()
            .map(|f| (f.line, f.item))
            .collect()
    }

    #[test]
    fn finds_a_tuple_struct_by_line() {
        assert_eq!(
            found("use x;\n\npub struct AgentId(pub String);\n", &["AgentId"]),
            vec![(3, "struct AgentId".to_string())]
        );
    }

    #[test]
    fn finds_every_defining_item_kind() {
        let text = "struct A;\nenum B { V }\nunion C { f: u8 }\ntype D = u8;\ntrait E {}\n";
        assert_eq!(found(text, &["A", "B", "C", "D", "E"]).len(), 5);
    }

    #[test]
    fn finds_raw_identifiers_nested_modules_and_function_bodies() {
        let text = "pub struct r#AgentId;\nmod m { pub struct Case; }\nfn f() { struct Agent; }\n";
        assert_eq!(
            found(text, &["AgentId", "Case", "Agent"]),
            vec![
                (1, "struct AgentId".to_string()),
                (2, "struct Case".to_string()),
                (3, "struct Agent".to_string()),
            ]
        );
    }

    #[test]
    fn finds_a_rename_to_a_model_name_but_not_a_plain_use() {
        let text = "use a::Handmade as AgentId;\nuse b10x_canon::CaseId;\nuse m::Case as Case;\n";
        assert_eq!(
            found(text, &["AgentId", "CaseId", "Case"]),
            vec![(1, "use Handmade as AgentId".to_string())]
        );
    }

    #[test]
    fn ignores_literals_comments_and_longer_names() {
        let text = "// struct Commission\n/* struct AgentId; */\n/// struct CaseId;\n\
                    const S: &str = \"struct Commission\";\npub struct CommissionRecord;\n";
        assert!(found(text, &["Commission", "AgentId", "CaseId"]).is_empty());
    }
}
