#![forbid(unsafe_code)]

//! Repository checks for Loom.
//!
//! The run model is generated by `ess generate synthesize` into `generated/rust/loom/`.
//! `generate` rewrites that tree from `ess/`; `drift` fails when the committed tree differs from a
//! fresh synthesis, naming the differing files; `no-hand-model` fails, naming file and line, when
//! a `.rs` file anywhere under `crates/loom-executor/src` (parsed as written: no `cfg` is evaluated and no
//! macro is expanded) holds, at any depth (nested modules and function bodies included):
//!
//! - a `struct`, `enum`, `union`, `type` or `trait` named after a reserved type;
//! - a `use … as <name>` that renames something to a reserved type;
//! - inside any macro's tokens, a type keyword directly followed by a reserved name, or an
//!   argument that is a reserved name alone (`model!(Selection)`);
//! - an `include!`, or a module with a `#[path]` attribute, whose source the scan cannot read.
//!
//! Comments and string literals are not code and are not read. Generated code is not scanned.
//!
//! Ported from Commission's `loom-commission-xtask` (beyond10x/commission `174bf07`). The reserved
//! names are those `ess specify compile` reports, so a type a later story declares in `ess/` is
//! covered before it is generated, together with every type the generated crate declares
//! (`SessionData`, `AnySession`, `SessionSnapshot`, …), as Commission's check reserves.
//!
//! `release-check --tag <tag>` fails unless the tag is the workspace version and `CHANGELOG.md`
//! has its entry; `.github/workflows/release.yml` runs it on every pushed tag (see `release`).

use clap::{Parser, Subcommand};
use std::collections::BTreeSet;
use std::fs;
use std::io;
use std::path::{Path, PathBuf};
use std::process::{Command as Process, ExitCode};
use std::time::{SystemTime, UNIX_EPOCH};
use syn::ext::IdentExt;
use syn::visit::Visit;

mod release;

/// Where the generated crate is committed, relative to the repository root.
const GENERATED: &str = "generated/rust/loom";
/// The specification, relative to the repository root.
const SPECIFICATION: &str = "ess";
/// The sources that must not define a model type, relative to the repository root.
const HAND_MODEL_SOURCES: [&str; 1] = ["crates/loom-executor/src"];
/// The name `b10x-loom-executor` re-exports the generated crate under.
const MODEL_REEXPORT: &str = "model";
/// Synthesis state: per-run anchor id, inode and absolute root. Never compared, never committed.
const ESS_OUTPUT: &str = ".ess-output";
/// The sections of the compiled specification whose keys name a generated type.
const DECLARATION_SECTIONS: [&str; 6] =
    ["types", "entities", "commands", "events", "errors", "views"];

#[derive(Debug, Parser)]
#[command(name = "loom-xtask", about = "Repository checks for Loom")]
struct Cli {
    /// Repository root. Defaults to the nearest ancestor of the current directory holding
    /// `ess/ess-inputs.yaml`.
    #[arg(long, global = true)]
    root: Option<PathBuf>,
    /// The `ess` executable.
    #[arg(long, global = true, default_value = "ess")]
    ess: PathBuf,
    #[command(subcommand)]
    command: Command,
}

#[derive(Debug, Subcommand)]
enum Command {
    /// Regenerate intake's Rust model, including the confinement contract.
    IntakeGenerate {
        #[command(flatten)]
        scratch: Scratch,
    },
    /// Check intake's generated Rust model against its specification.
    IntakeDrift {
        #[command(flatten)]
        scratch: Scratch,
    },
    /// Rewrite `generated/rust/loom/` from a fresh synthesis of `ess/`.
    Generate {
        #[command(flatten)]
        scratch: Scratch,
    },
    /// Fail when `generated/rust/loom/` differs from a fresh synthesis of `ess/`, naming each
    /// differing file.
    Drift {
        #[command(flatten)]
        scratch: Scratch,
        /// The committed tree to compare. Defaults to `<root>/generated/rust/loom`.
        #[arg(long)]
        generated: Option<PathBuf>,
    },
    /// Fail when a source file of `b10x-loom-executor` defines, or renames something to, a type `ess/`
    /// declares (its name with the domain prefix removed) or a type the generated crate declares.
    NoHandModel {
        /// A source directory to scan; repeat for more. Defaults to `<root>/crates/loom-executor/src`.
        #[arg(long)]
        src: Vec<PathBuf>,
        /// The generated crate whose type names are reserved as well. Defaults to
        /// `<root>/generated/rust/loom`.
        #[arg(long)]
        generated: Option<PathBuf>,
    },
    /// Fail unless a release tag is a bare version equal to `[workspace.package] version` in
    /// `<root>/Cargo.toml`, and `<root>/CHANGELOG.md` has a `## [<tag>]` entry.
    ReleaseCheck {
        /// The release tag, e.g. `0.1.0`.
        #[arg(long)]
        tag: String,
    },
}

#[derive(Debug, clap::Args)]
struct Scratch {
    /// Directory for the temporary regeneration tree. Defaults to
    /// `$CARGO_TARGET_DIR/loom-xtask`, or `<root>/target/loom-xtask`.
    #[arg(long)]
    scratch: Option<PathBuf>,
}

fn main() -> ExitCode {
    let cli = Cli::parse();
    match run(cli) {
        Ok(()) => ExitCode::SUCCESS,
        Err(message) => {
            eprintln!("{message}");
            ExitCode::FAILURE
        }
    }
}

fn run(cli: Cli) -> Result<(), String> {
    let root = match cli.root {
        Some(root) => root,
        None => find_root()?,
    };
    match cli.command {
        Command::Generate { scratch } => {
            generate(&root, &cli.ess, &scratch, SPECIFICATION, GENERATED)
        }
        Command::IntakeGenerate { scratch } => generate(
            &root,
            &cli.ess,
            &scratch,
            "ess/intake",
            "generated/rust/intake",
        ),
        Command::IntakeDrift { scratch } => drift(
            &root,
            &cli.ess,
            &scratch,
            &root.join("generated/rust/intake"),
            "ess/intake",
        ),
        Command::Drift { scratch, generated } => drift(
            &root,
            &cli.ess,
            &scratch,
            &generated.unwrap_or_else(|| root.join(GENERATED)),
            SPECIFICATION,
        ),
        Command::NoHandModel { src, generated } => no_hand_model(
            &root,
            &cli.ess,
            &if src.is_empty() {
                HAND_MODEL_SOURCES
                    .iter()
                    .map(|dir| root.join(dir))
                    .collect()
            } else {
                src
            },
            &generated.unwrap_or_else(|| root.join(GENERATED)),
        ),
        Command::ReleaseCheck { tag } => release::release_check(&root, &tag),
    }
}

fn find_root() -> Result<PathBuf, String> {
    let cwd = std::env::current_dir().map_err(|e| format!("current directory: {e}"))?;
    cwd.ancestors()
        .find(|dir| dir.join(SPECIFICATION).join("ess-inputs.yaml").is_file())
        .map(Path::to_path_buf)
        .ok_or_else(|| {
            format!(
                "no ancestor of {} holds {SPECIFICATION}/ess-inputs.yaml; pass --root",
                cwd.display()
            )
        })
}

/// Synthesizes into scratch, stages the complete tree beside the target, then swaps it in by
/// rename. The committed tree is never removed before its replacement is complete.
fn generate(
    root: &Path,
    ess: &Path,
    scratch: &Scratch,
    specification: &str,
    generated: &str,
) -> Result<(), String> {
    let fresh = Regeneration::synthesize(root, ess, scratch, specification)?;
    let target = root.join(generated);
    let parent = target
        .parent()
        .ok_or_else(|| format!("{} has no parent", target.display()))?;
    fs::create_dir_all(parent).map_err(|e| format!("create {}: {e}", parent.display()))?;

    let staging = Staging::new(parent.join(format!(".loom.staging-{}", std::process::id())))?;
    for relative in tree_files(&fresh.dir)? {
        let to = staging.dir.join(&relative);
        if let Some(dir) = to.parent() {
            fs::create_dir_all(dir).map_err(|e| format!("create {}: {e}", dir.display()))?;
        }
        fs::copy(fresh.dir.join(&relative), &to)
            .map_err(|e| format!("write {}: {e}", to.display()))?;
    }

    if !target.exists() {
        fs::rename(&staging.dir, &target)
            .map_err(|e| format!("move the new tree to {}: {e}", target.display()))?;
    } else {
        let old = parent.join(format!(".loom.old-{}", std::process::id()));
        if old.exists() {
            fs::remove_dir_all(&old).map_err(|e| format!("remove {}: {e}", old.display()))?;
        }
        fs::rename(&target, &old).map_err(|e| format!("move {} aside: {e}", target.display()))?;
        if let Err(error) = fs::rename(&staging.dir, &target) {
            let restored = fs::rename(&old, &target);
            return Err(format!(
                "move the new tree to {}: {error}; previous tree {}",
                target.display(),
                match restored {
                    Ok(()) => "restored".to_string(),
                    Err(e) => format!("left at {}: {e}", old.display()),
                }
            ));
        }
        fs::remove_dir_all(&old).map_err(|e| {
            format!(
                "{generated} regenerated, but the previous tree at {} could not be removed: {e}",
                old.display()
            )
        })?;
    }
    println!("{generated}: regenerated from {specification}/");
    Ok(())
}

/// A staging tree beside the target, removed when dropped unless it was moved into place.
struct Staging {
    dir: PathBuf,
}

impl Staging {
    fn new(dir: PathBuf) -> Result<Self, String> {
        if dir.exists() {
            fs::remove_dir_all(&dir).map_err(|e| format!("remove {}: {e}", dir.display()))?;
        }
        Ok(Self { dir })
    }
}

impl Drop for Staging {
    fn drop(&mut self) {
        if self.dir.exists() {
            let _ = fs::remove_dir_all(&self.dir);
        }
    }
}

fn drift(
    root: &Path,
    ess: &Path,
    scratch: &Scratch,
    committed: &Path,
    specification: &str,
) -> Result<(), String> {
    let fresh = Regeneration::synthesize(root, ess, scratch, specification)?;
    let differences = compare_trees(&fresh.dir, committed)?;
    if differences.is_empty() {
        println!("{}: no drift from {specification}/", committed.display());
        return Ok(());
    }
    let mut message = format!(
        "{} drifted from a fresh synthesis of {specification}/ (regenerate this model):",
        committed.display()
    );
    for difference in &differences {
        message.push_str("\n  ");
        message.push_str(&difference.to_string());
    }
    Err(message)
}

/// A fresh synthesis in its own directory under the scratch root, removed when dropped.
struct Regeneration {
    dir: PathBuf,
}

impl Regeneration {
    fn synthesize(
        root: &Path,
        ess: &Path,
        scratch: &Scratch,
        specification: &str,
    ) -> Result<Self, String> {
        let scratch = match &scratch.scratch {
            Some(dir) => dir.clone(),
            None => default_scratch(root),
        };
        fs::create_dir_all(&scratch)
            .map_err(|e| format!("create scratch {}: {e}", scratch.display()))?;
        let nanos = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .map(|d| d.as_nanos())
            .unwrap_or_default();
        let regeneration = Self {
            dir: scratch.join(format!("regen-{}-{nanos}", std::process::id())),
        };
        let output = Process::new(ess)
            .args(["generate", "synthesize", "--path"])
            .arg(root.join(specification))
            .args(["--target", "rust", "--layout", "crate", "--out"])
            .arg(&regeneration.dir)
            .output()
            .map_err(|e| format!("run {}: {e}", ess.display()))?;
        if !output.status.success() {
            return Err(format!(
                "`{} generate synthesize` failed ({}):\n{}{}",
                ess.display(),
                output.status,
                String::from_utf8_lossy(&output.stdout),
                String::from_utf8_lossy(&output.stderr)
            ));
        }
        Ok(regeneration)
    }
}

impl Drop for Regeneration {
    fn drop(&mut self) {
        if self.dir.exists() {
            let _ = fs::remove_dir_all(&self.dir);
        }
    }
}

fn default_scratch(root: &Path) -> PathBuf {
    std::env::var_os("CARGO_TARGET_DIR")
        .map(PathBuf::from)
        .unwrap_or_else(|| root.join("target"))
        .join("loom-xtask")
}

#[derive(Debug, PartialEq, Eq)]
enum Difference {
    /// Synthesis writes it; the committed tree lacks it.
    Missing(String),
    /// The committed tree has it; synthesis does not write it.
    Unexpected(String),
    /// Both have it, with different bytes.
    Changed(String),
}

impl std::fmt::Display for Difference {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Missing(path) => write!(f, "{path}: missing from the committed tree"),
            Self::Unexpected(path) => write!(f, "{path}: not produced by synthesis"),
            Self::Changed(path) => write!(f, "{path}: differs from synthesis"),
        }
    }
}

/// Compares two trees file by file, in path order, ignoring `.ess-output/` at the top of either.
fn compare_trees(expected: &Path, actual: &Path) -> Result<Vec<Difference>, String> {
    let expected_files = tree_files(expected)?;
    let actual_files = if actual.is_dir() {
        tree_files(actual)?
    } else {
        BTreeSet::new()
    };
    let mut differences = Vec::new();
    for path in expected_files.union(&actual_files) {
        let name = path.to_string_lossy().into_owned();
        match (expected_files.contains(path), actual_files.contains(path)) {
            (true, false) => differences.push(Difference::Missing(name)),
            (false, true) => differences.push(Difference::Unexpected(name)),
            _ => {
                let want = read(&expected.join(path))?;
                let have = read(&actual.join(path))?;
                if want != have {
                    differences.push(Difference::Changed(name));
                }
            }
        }
    }
    Ok(differences)
}

fn read(path: &Path) -> Result<Vec<u8>, String> {
    fs::read(path).map_err(|e| format!("read {}: {e}", path.display()))
}

/// Every file under `root`, relative to it, leaving out `.ess-output/`.
fn tree_files(root: &Path) -> Result<BTreeSet<PathBuf>, String> {
    let mut files = BTreeSet::new();
    walk(root, Path::new(""), &mut files)
        .map_err(|e| format!("read tree {}: {e}", root.display()))?;
    Ok(files)
}

fn walk(root: &Path, relative: &Path, files: &mut BTreeSet<PathBuf>) -> io::Result<()> {
    for entry in fs::read_dir(root.join(relative))? {
        let entry = entry?;
        let path = relative.join(entry.file_name());
        if path == Path::new(ESS_OUTPUT) {
            continue;
        }
        if entry.file_type()?.is_dir() {
            walk(root, &path, files)?;
        } else {
            files.insert(path);
        }
    }
    Ok(())
}

/// The `.rs` files under `dir`, each with its path and text.
fn rust_sources(dir: &Path) -> Result<Vec<(PathBuf, String)>, String> {
    let mut files = BTreeSet::new();
    walk(dir, Path::new(""), &mut files)
        .map_err(|e| format!("read sources {}: {e}", dir.display()))?;
    files
        .into_iter()
        .filter(|p| p.extension().is_some_and(|ext| ext == "rs"))
        .map(|relative| {
            let path = dir.join(relative);
            fs::read_to_string(&path)
                .map(|text| (path.clone(), text))
                .map_err(|e| format!("read {}: {e}", path.display()))
        })
        .collect()
}

fn parse(path: &Path, text: &str) -> Result<syn::File, String> {
    syn::parse_file(text).map_err(|e| {
        format!(
            "{}:{}: not readable as Rust, so it cannot be checked: {e}",
            path.display(),
            e.span().start().line
        )
    })
}

/// The names `ess/` declares, read from `ess specify compile --format json`.
fn specified_type_names(root: &Path, ess: &Path) -> Result<BTreeSet<String>, String> {
    let output = Process::new(ess)
        .args(["specify", "compile", "--path"])
        .arg(root.join(SPECIFICATION))
        .args(["--format", "json"])
        .output()
        .map_err(|e| format!("run {}: {e}", ess.display()))?;
    if !output.status.success() {
        return Err(format!(
            "`{} specify compile` failed ({}):\n{}{}",
            ess.display(),
            output.status,
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr)
        ));
    }
    let compiled: serde_json::Value = serde_json::from_slice(&output.stdout)
        .map_err(|e| format!("`{} specify compile` printed no JSON: {e}", ess.display()))?;
    let names = type_names(&compiled)?;
    if names.is_empty() {
        return Err(format!(
            "{SPECIFICATION}/ declares no type, so there is nothing to check against"
        ));
    }
    Ok(names)
}

/// Every key of the compiled specification's declaration sections, with its domain prefix
/// removed and the remaining segments joined: `loom.run.Session` is `Session`, and
/// `loom.run.Session.State` is `SessionState`, as the generated crate names them.
fn type_names(compiled: &serde_json::Value) -> Result<BTreeSet<String>, String> {
    let domains: Vec<&String> = compiled
        .get("domains")
        .and_then(serde_json::Value::as_object)
        .ok_or("the compiled specification has no `domains` object")?
        .keys()
        .collect();
    let mut names = BTreeSet::new();
    for section in DECLARATION_SECTIONS {
        let Some(declared) = compiled.get(section).and_then(serde_json::Value::as_object) else {
            continue;
        };
        for key in declared.keys() {
            let local = domains
                .iter()
                .filter_map(|domain| key.strip_prefix(domain.as_str())?.strip_prefix('.'))
                .min_by_key(|local| local.len())
                .ok_or_else(|| {
                    format!("`{section}` entry `{key}` lies in no domain of the specification")
                })?;
            names.insert(local.split('.').collect::<String>());
        }
    }
    Ok(names)
}

/// The type names the generated crate declares at the top of each of its files, and the trait
/// names it declares in the inline modules below them (`run::session_state::Marker`), descending
/// only into `pub` modules: a private module such as `session_state::sealed` exports nothing, so
/// its `Sealed` names no model type. A nested struct is a state marker (`session_state::Active`)
/// whose name is a state, not a model type, so it is not reserved. Ported from loom-commission-xtask.
fn generated_type_names(generated: &Path) -> Result<BTreeSet<String>, String> {
    /// The module's items, when it is `pub` and inline.
    fn public_items(item: &syn::ItemMod) -> Option<&[syn::Item]> {
        match (&item.vis, &item.content) {
            (syn::Visibility::Public(_), Some((_, items))) => Some(items),
            _ => None,
        }
    }

    fn nested_traits(items: &[syn::Item], names: &mut BTreeSet<String>) {
        for item in items {
            match item {
                syn::Item::Trait(item) => {
                    names.insert(item.ident.unraw().to_string());
                }
                syn::Item::TraitAlias(item) => {
                    names.insert(item.ident.unraw().to_string());
                }
                syn::Item::Mod(item) => {
                    if let Some(items) = public_items(item) {
                        nested_traits(items, names);
                    }
                }
                _ => {}
            }
        }
    }

    let mut names = BTreeSet::new();
    for (path, text) in rust_sources(&generated.join("src"))? {
        for item in parse(&path, &text)?.items {
            let ident = match item {
                syn::Item::Struct(item) => item.ident,
                syn::Item::Enum(item) => item.ident,
                syn::Item::Union(item) => item.ident,
                syn::Item::Type(item) => item.ident,
                syn::Item::Trait(item) => item.ident,
                syn::Item::TraitAlias(item) => item.ident,
                syn::Item::Mod(item) => {
                    if let Some(items) = public_items(&item) {
                        nested_traits(items, &mut names);
                    }
                    continue;
                }
                _ => continue,
            };
            names.insert(ident.unraw().to_string());
        }
    }
    if names.is_empty() {
        return Err(format!(
            "{}: declares no type, so there is nothing to check against; run `task generate`",
            generated.display()
        ));
    }
    Ok(names)
}

fn no_hand_model(
    root: &Path,
    ess: &Path,
    srcs: &[PathBuf],
    generated: &Path,
) -> Result<(), String> {
    let mut names = specified_type_names(root, ess)?;
    names.extend(generated_type_names(generated)?);
    let mut findings = Vec::new();
    let mut sources = Vec::new();
    for src in srcs {
        sources.extend(rust_sources(src)?);
    }
    for (path, text) in sources {
        for found in hand_model_items(&parse(&path, &text)?, &names) {
            let problem = match found.problem {
                Problem::ModelType => format!(
                    "is a hand-written model type; take it from the generated crate \
                     (`b10x_loom_executor::{MODEL_REEXPORT}`)"
                ),
                Problem::Include => "brings in source this check cannot read; write the items \
                                     in a scanned file instead"
                    .to_string(),
                Problem::PathAttribute => "loads a module file this check does not follow; \
                                           remove the attribute so the module lies under a \
                                           scanned directory"
                    .to_string(),
            };
            findings.push(format!(
                "{}:{}: `{}` {problem}",
                path.display(),
                found.line,
                found.item
            ));
        }
    }
    if findings.is_empty() {
        for src in srcs {
            println!(
                "{}: no hand-written model type ({} reserved type names checked)",
                src.display(),
                names.len()
            );
        }
        Ok(())
    } else {
        Err(findings.join("\n"))
    }
}

#[derive(Debug, PartialEq, Eq)]
struct Found {
    line: usize,
    item: String,
    problem: Problem,
}

/// Why a finding is refused.
#[derive(Debug, PartialEq, Eq)]
enum Problem {
    /// A definition of, or a rename to, a specified type's name.
    ModelType,
    /// `include!`, whose source the check cannot read.
    Include,
    /// A `#[path]` module, whose file the check does not follow.
    PathAttribute,
}

/// The keywords that open a type definition, in source or in a macro's tokens.
const TYPE_KEYWORDS: [&str; 5] = ["struct", "enum", "type", "union", "trait"];

/// Every item definition named after a specified type, and every `use … as <name>` that gives
/// something else a specified type's name, anywhere in the file. Raw identifiers count as the
/// identifier; literals and comments are not code and are not read.
///
/// Macros are not expanded. Instead the tokens of every macro — `macro_rules!` bodies and every
/// invocation, in any position — are read twice: for a type keyword directly followed by a
/// reserved name, and for an argument that is a reserved name alone (`model!(Selection)`, which a
/// macro taking `$name:ident` turns into a definition). Both are refused. `include!` is refused
/// outright, and so is a module carrying a `#[path]` attribute (directly or through `cfg_attr`):
/// both bring in source from a file the scan does not read.
fn hand_model_items(file: &syn::File, names: &BTreeSet<String>) -> Vec<Found> {
    struct Scan<'a> {
        names: &'a BTreeSet<String>,
        found: Vec<Found>,
    }

    impl Scan<'_> {
        fn definition(&mut self, keyword: &str, ident: &syn::Ident) {
            let name = ident.unraw().to_string();
            if self.names.contains(&name) {
                self.found.push(Found {
                    line: ident.span().start().line,
                    item: format!("{keyword} {name}"),
                    problem: Problem::ModelType,
                });
            }
        }

        /// A type keyword directly followed by a specified name, at any depth of `tokens`.
        fn macro_tokens(&mut self, tokens: proc_macro2::TokenStream) {
            let mut keyword: Option<String> = None;
            for tree in tokens {
                match tree {
                    proc_macro2::TokenTree::Ident(ident) => {
                        if let Some(keyword) = keyword.take() {
                            let name = ident.unraw().to_string();
                            if self.names.contains(&name) {
                                self.found.push(Found {
                                    line: ident.span().start().line,
                                    item: format!("{keyword} {name}"),
                                    problem: Problem::ModelType,
                                });
                            }
                        }
                        let word = ident.to_string();
                        if TYPE_KEYWORDS.contains(&word.as_str()) {
                            keyword = Some(word);
                        }
                    }
                    proc_macro2::TokenTree::Group(group) => {
                        keyword = None;
                        self.macro_tokens(group.stream());
                    }
                    _ => keyword = None,
                }
            }
        }

        /// A specified name passed to macro `name` as an identifier argument: an argument, at any
        /// depth of `tokens`, that is that one identifier and nothing else (`model!(Selection)`,
        /// `model! { a, Selection }`). Arguments are separated by `,` and `;`.
        fn macro_arguments(&mut self, name: &str, tokens: proc_macro2::TokenStream) {
            let mut argument: Vec<proc_macro2::TokenTree> = Vec::new();
            let close = |scan: &mut Self, argument: &mut Vec<proc_macro2::TokenTree>| {
                if let [proc_macro2::TokenTree::Ident(ident)] = argument.as_slice() {
                    let ident_name = ident.unraw().to_string();
                    if scan.names.contains(&ident_name) {
                        scan.found.push(Found {
                            line: ident.span().start().line,
                            item: format!("{name}!({ident_name})"),
                            problem: Problem::ModelType,
                        });
                    }
                }
                argument.clear();
            };
            for tree in tokens {
                match tree {
                    proc_macro2::TokenTree::Punct(punct)
                        if punct.as_char() == ',' || punct.as_char() == ';' =>
                    {
                        close(self, &mut argument);
                    }
                    proc_macro2::TokenTree::Group(group) => {
                        self.macro_arguments(name, group.stream());
                        argument.push(proc_macro2::TokenTree::Group(group));
                    }
                    other => argument.push(other),
                }
            }
            close(self, &mut argument);
        }

        /// Whether `tokens` hold `path =` at their top level, as a `cfg_attr` that sets a path does.
        fn sets_path(tokens: &proc_macro2::TokenStream) -> bool {
            let trees: Vec<_> = tokens.clone().into_iter().collect();
            trees.windows(2).any(|pair| {
                matches!(&pair[0], proc_macro2::TokenTree::Ident(ident) if ident == "path")
                    && matches!(&pair[1], proc_macro2::TokenTree::Punct(punct) if punct.as_char() == '=')
            })
        }
    }

    impl<'ast> Visit<'ast> for Scan<'_> {
        fn visit_item_struct(&mut self, item: &'ast syn::ItemStruct) {
            self.definition("struct", &item.ident);
            syn::visit::visit_item_struct(self, item);
        }
        fn visit_item_enum(&mut self, item: &'ast syn::ItemEnum) {
            self.definition("enum", &item.ident);
            syn::visit::visit_item_enum(self, item);
        }
        fn visit_item_union(&mut self, item: &'ast syn::ItemUnion) {
            self.definition("union", &item.ident);
            syn::visit::visit_item_union(self, item);
        }
        fn visit_item_type(&mut self, item: &'ast syn::ItemType) {
            self.definition("type", &item.ident);
            syn::visit::visit_item_type(self, item);
        }
        fn visit_item_trait(&mut self, item: &'ast syn::ItemTrait) {
            self.definition("trait", &item.ident);
            syn::visit::visit_item_trait(self, item);
        }
        fn visit_item_trait_alias(&mut self, item: &'ast syn::ItemTraitAlias) {
            self.definition("trait", &item.ident);
            syn::visit::visit_item_trait_alias(self, item);
        }
        fn visit_use_rename(&mut self, rename: &'ast syn::UseRename) {
            let from = rename.ident.unraw().to_string();
            let to = rename.rename.unraw().to_string();
            if from != to && self.names.contains(&to) {
                self.found.push(Found {
                    line: rename.rename.span().start().line,
                    item: format!("use {from} as {to}"),
                    problem: Problem::ModelType,
                });
            }
        }
        fn visit_macro(&mut self, mac: &'ast syn::Macro) {
            if let Some(last) = mac.path.segments.last()
                && last.ident == "include"
            {
                self.found.push(Found {
                    line: last.ident.span().start().line,
                    item: "include!".to_string(),
                    problem: Problem::Include,
                });
            }
            self.macro_tokens(mac.tokens.clone());
            let name = mac
                .path
                .segments
                .last()
                .map(|last| last.ident.unraw().to_string())
                .unwrap_or_default();
            self.macro_arguments(&name, mac.tokens.clone());
            syn::visit::visit_macro(self, mac);
        }
        fn visit_item_mod(&mut self, item: &'ast syn::ItemMod) {
            for attr in &item.attrs {
                let form = if attr.path().is_ident("path") {
                    Some("#[path = …]")
                } else if attr.path().is_ident("cfg_attr")
                    && matches!(&attr.meta, syn::Meta::List(list) if Self::sets_path(&list.tokens))
                {
                    Some("#[cfg_attr(…, path = …)]")
                } else {
                    None
                };
                if let Some(form) = form {
                    self.found.push(Found {
                        line: attr.pound_token.spans[0].start().line,
                        item: format!("{form} mod {}", item.ident.unraw()),
                        problem: Problem::PathAttribute,
                    });
                }
            }
            syn::visit::visit_item_mod(self, item);
        }
    }

    let mut scan = Scan {
        names,
        found: Vec::new(),
    };
    scan.visit_file(file);
    scan.found
}

#[cfg(test)]
mod tests {
    use super::*;

    fn names(list: &[&str]) -> BTreeSet<String> {
        list.iter().map(|n| n.to_string()).collect()
    }

    fn found(text: &str, list: &[&str]) -> Vec<(usize, String)> {
        let file = syn::parse_file(text).expect("parse");
        hand_model_items(&file, &names(list))
            .into_iter()
            .map(|f| (f.line, f.item))
            .collect()
    }

    #[test]
    fn finds_a_struct_by_line() {
        assert_eq!(
            found(
                "use x;\n\npub struct Selection { pub action: String }\n",
                &["Selection"]
            ),
            vec![(3, "struct Selection".to_string())]
        );
    }

    #[test]
    fn finds_every_defining_item_kind() {
        let text = "struct A;\nenum B { V }\nunion C { f: u8 }\ntype D = u8;\ntrait E {}\n";
        assert_eq!(found(text, &["A", "B", "C", "D", "E"]).len(), 5);
    }

    #[test]
    fn finds_raw_identifiers_nested_modules_and_function_bodies() {
        let text =
            "pub struct r#SessionId;\nmod m { pub struct Turn; }\nfn f() { struct Session; }\n";
        assert_eq!(
            found(text, &["SessionId", "Turn", "Session"]),
            vec![
                (1, "struct SessionId".to_string()),
                (2, "struct Turn".to_string()),
                (3, "struct Session".to_string()),
            ]
        );
    }

    #[test]
    fn finds_a_rename_to_a_model_name_but_not_a_plain_use() {
        let text =
            "use a::Handmade as Session;\nuse model::run::Turn;\nuse m::Selection as Selection;\n";
        assert_eq!(
            found(text, &["Session", "Turn", "Selection"]),
            vec![(1, "use Handmade as Session".to_string())]
        );
    }

    #[test]
    fn finds_a_name_passed_alone_to_a_macro_but_not_a_path_through_it() {
        let text = "model!(Selection);\nfn f() { assert_eq!(s.state(), SessionState::Active); }\n\
                    m! { a, (Turn) }\n";
        assert_eq!(
            found(text, &["Selection", "SessionState", "Turn"]),
            vec![
                (1, "model!(Selection)".to_string()),
                (3, "m!(Turn)".to_string())
            ]
        );
    }

    #[test]
    fn ignores_literals_comments_and_longer_names() {
        let text = "// struct Session\n/* struct Turn; */\n/// struct Selection;\n\
                    const S: &str = \"struct Session\";\npub struct SessionRecord;\n";
        assert!(found(text, &["Session", "Turn", "Selection"]).is_empty());
    }

    #[test]
    fn type_names_strip_the_domain_and_join_state_types() {
        let compiled = serde_json::json!({
            "domains": {"loom.run": {}},
            "types": {"loom.run.SessionId": {}, "loom.run.Session.State": {}},
            "entities": {"loom.run.Session": {}},
            "commands": {},
        });
        assert_eq!(
            type_names(&compiled).expect("names"),
            names(&["Session", "SessionId", "SessionState"])
        );
    }

    #[test]
    fn type_names_refuse_a_key_outside_every_domain() {
        let compiled = serde_json::json!({
            "domains": {"loom.run": {}},
            "types": {"other.Thing": {}},
        });
        let error = type_names(&compiled).expect_err("a key outside every domain");
        assert!(error.contains("other.Thing"), "{error}");
    }
}
