[package]
name = "b10x-loom"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
b10x-commission = { git = "https://github.com/beyond10x/commission", branch = "main" }
loom = { path = "../../generated/rust/loom" }

[dev-dependencies]
b10x-commission-testkit = { git = "https://github.com/beyond10x/commission", branch = "main" }
