#![forbid(unsafe_code)]

//! Generates the reference pages of the Commission documentation site from the ESS specification,
//! checks the committed pages for drift, and writes a built site's publication provenance. The
//! site build is the only Node in the repository; everything the site can derive is written here,
//! into `website/docs/reference/`.
use std::{
    collections::BTreeMap,
    fmt::Write as _,
    fs,
    path::{Path, PathBuf},
    process::{Command, ExitCode},
};

use clap::{Parser, Subcommand};
use serde_json::{Value, json};

const REFERENCE_DIR: &str = "website/docs/reference";
const DOCS_DIR: &str = "website/docs";

/// Whether a line opens an admonition with a raw title, `^:::[a-z]+ +\S`. Docusaurus renders such
/// a title as body text; the bracket form `:::note[Title]` is the one that works.
fn is_raw_admonition(line: &str) -> bool {
    let Some(rest) = line.strip_prefix(":::") else {
        return false;
    };
    let kind = rest.bytes().take_while(u8::is_ascii_lowercase).count();
    let after = &rest[kind..];
    let spaces = after.bytes().take_while(|b| *b == b' ').count();
    kind > 0
        && spaces > 0
        && after[spaces..]
            .chars()
            .next()
            .is_some_and(|c| !c.is_whitespace())
}

/// Every `path:line` under `dir` (Markdown and MDX, recursively) that opens a raw admonition.
fn raw_admonitions(dir: &Path) -> Result<Vec<String>> {
    let mut found = Vec::new();
    let mut pending = vec![dir.to_path_buf()];
    while let Some(next) = pending.pop() {
        let mut entries: Vec<_> = fs::read_dir(&next)
            .map_err(|e| format!("{}: {e}", next.display()))?
            .map(|entry| entry.map(|e| e.path()).map_err(|e| e.to_string()))
            .collect::<Result<_>>()?;
        entries.sort();
        for path in entries {
            if path.is_dir() {
                pending.push(path);
            } else if path
                .extension()
                .is_some_and(|ext| ext == "md" || ext == "mdx")
            {
                let content =
                    fs::read_to_string(&path).map_err(|e| format!("{}: {e}", path.display()))?;
                for (index, line) in content.lines().enumerate() {
                    if is_raw_admonition(line) {
                        found.push(format!("{}:{}", path.display(), index + 1));
                    }
                }
            }
        }
    }
    found.sort();
    Ok(found)
}
const MARKER: &str = "generated by commission-docs, do not edit";
const DOMAIN_MODEL: &str = "domain-model.md";
const TYPES: &str = "types.md";
const DOMAIN_GRAPH: &str = "domain-graph.json";

type Result<T> = std::result::Result<T, String>;
type Pages = BTreeMap<&'static str, String>;

#[derive(Parser)]
#[command(about = "Generate and check the Commission documentation reference pages")]
struct Cli {
    #[command(subcommand)]
    command: Action,
}

#[derive(Subcommand)]
enum Action {
    /// Regenerate website/docs/reference/ from the ESS specification in ess/.
    Generate {
        /// Compare instead of writing; fail when a page differs, is missing or is not generated.
        #[arg(long)]
        check: bool,
        /// The repository root.
        #[arg(long, default_value = ".")]
        root: PathBuf,
        /// The `ess` executable that compiles the specification.
        #[arg(long, default_value = "ess")]
        ess: PathBuf,
        /// Read compiled ESS IR (JSON) from this file instead of running `ess`.
        #[arg(long)]
        ir: Option<PathBuf>,
    },
    /// Write the publication provenance of a built site: `.well-known/b10x-site.json`.
    Provenance {
        /// The built site directory (Docusaurus writes `website/build`).
        #[arg(long)]
        site: PathBuf,
        /// The full Git commit the site was built from.
        #[arg(long)]
        commit: String,
    },
}

const BASE_URL: &str = "/commission/";

/// Write `.well-known/b10x-site.json` and `.nojekyll` into a built site, bound to `commit`.
fn provenance(site: &Path, commit: &str) -> Result<PathBuf> {
    if !(commit.len() == 40
        && commit.bytes().all(|b| b.is_ascii_hexdigit())
        && commit != "0".repeat(40))
    {
        return Err("commit must be a nonzero full Git revision".into());
    }
    if !site.join("index.html").is_file() {
        return Err(format!(
            "{}: no built site (index.html missing)",
            site.display()
        ));
    }
    let manifest = serde_json::json!({
        "schema": "b10x-project-site/v1",
        "repository": "commission",
        "commit": commit,
        "baseUrl": BASE_URL,
    });
    let dir = site.join(".well-known");
    fs::create_dir_all(&dir).map_err(|e| format!("{}: {e}", dir.display()))?;
    let path = dir.join("b10x-site.json");
    let bytes = serde_json::to_vec_pretty(&manifest).map_err(|e| e.to_string())?;
    fs::write(&path, bytes).map_err(|e| format!("{}: {e}", path.display()))?;
    fs::write(site.join(".nojekyll"), "").map_err(|e| format!("{}: {e}", site.display()))?;
    Ok(path)
}

/// `ess --version`, as it prints it (`ess 0.52.0`). CI pins the release.
fn ess_version(ess: &Path) -> Result<String> {
    let output = Command::new(ess)
        .arg("--version")
        .output()
        .map_err(|error| format!("running {}: {error}", ess.display()))?;
    let version = String::from_utf8_lossy(&output.stdout).trim().to_string();
    if !output.status.success() || version.is_empty() {
        return Err("`ess --version` printed no version".into());
    }
    Ok(version)
}

fn compile_ir(root: &Path, ess: &Path) -> Result<Value> {
    let output = Command::new(ess)
        .args(["specify", "compile", "--path"])
        .arg(root.join("ess"))
        .args(["--format", "json"])
        .output()
        .map_err(|error| format!("running {}: {error}", ess.display()))?;
    if !output.status.success() {
        return Err(format!(
            "`ess specify compile` failed: {}",
            String::from_utf8_lossy(&output.stderr).trim()
        ));
    }
    serde_json::from_slice(&output.stdout).map_err(|error| format!("reading ESS IR: {error}"))
}

fn field<'a>(value: &'a Value, key: &str) -> Result<&'a Value> {
    value
        .get(key)
        .ok_or_else(|| format!("ESS IR: missing `{key}`"))
}

fn text<'a>(value: &'a Value, key: &str) -> Result<&'a str> {
    field(value, key)?
        .as_str()
        .ok_or_else(|| format!("ESS IR: `{key}` is not a string"))
}

fn list<'a>(value: &'a Value, key: &str) -> Result<&'a [Value]> {
    field(value, key)?
        .as_array()
        .map(Vec::as_slice)
        .ok_or_else(|| format!("ESS IR: `{key}` is not a list"))
}

/// Free text from the specification, made safe for MDX.
fn prose(raw: &str) -> String {
    raw.replace('{', "\\{")
        .replace('}', "\\}")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
}

/// The heading anchor Docusaurus derives for a heading made of one name.
fn slug(name: &str) -> String {
    name.chars()
        .filter(|c| c.is_ascii_alphanumeric() || *c == '-' || *c == '_')
        .map(|c| c.to_ascii_lowercase())
        .collect()
}

struct Model<'a> {
    ir: &'a Value,
    prefixes: Vec<String>,
}

impl<'a> Model<'a> {
    fn new(ir: &'a Value) -> Result<Self> {
        let domains = field(ir, "domains")?
            .as_object()
            .ok_or("ESS IR: `domains` is not a map")?;
        let mut prefixes: Vec<String> = domains.keys().map(|d| format!("{d}.")).collect();
        prefixes.sort_by_key(|p| std::cmp::Reverse(p.len()));
        Ok(Self { ir, prefixes })
    }

    fn short<'n>(&self, name: &'n str) -> &'n str {
        self.prefixes
            .iter()
            .find_map(|p| name.strip_prefix(p.as_str()))
            .unwrap_or(name)
    }

    fn is_type(&self, name: &str) -> bool {
        self.ir["types"].get(name).is_some() && !name.ends_with(".State")
    }

    /// A type reference as Markdown; `types_page` is the link target for declared types.
    fn type_ref(&self, reference: &Value, types_page: &str) -> Result<String> {
        Ok(match text(reference, "kind")? {
            "primitive" => format!("`{}`", text(reference, "name")?),
            "declared" => {
                let name = text(reference, "name")?;
                let short = self.short(name);
                if short == "Unit" {
                    "none".to_string()
                } else if self.is_type(name) {
                    format!("[`{short}`]({types_page}#{})", slug(short))
                } else {
                    format!("`{short}`")
                }
            }
            "optional" => format!(
                "optional {}",
                self.type_ref(field(reference, "of")?, types_page)?
            ),
            "list" => format!(
                "list of {}",
                self.type_ref(field(reference, "of")?, types_page)?
            ),
            other => return Err(format!("ESS IR: unsupported type reference kind `{other}`")),
        })
    }
}

fn header(title: &str, description: &str, ir: &Value) -> Result<String> {
    Ok(format!(
        "---\ntitle: {}\ndescription: {}\n---\n\n\
         {{/* {MARKER}; regenerate with `task docs` */}}\n\n\
         :::note[Generated page]\n\n\
         This page is generated by `commission-docs` from the ESS specification in `ess/` \
         (system `{}`, version {}). Do not edit it by hand; run `task docs`.\n\n:::\n\n",
        // A JSON string is a valid YAML double-quoted scalar, whatever the text holds.
        Value::from(title),
        Value::from(description),
        text(ir, "system")?,
        field(ir, "version")?
    ))
}

fn render_domain_model(model: &Model) -> Result<String> {
    let ir = model.ir;
    let mut page = header(
        "Domain model",
        "The entities of the Commission specification, their fields, lifecycles and relations.",
        ir,
    )?;
    writeln!(
        page,
        "import domainGraph from './{DOMAIN_GRAPH}';\n\n# Domain model\n\n{}\n",
        prose(text(ir, "summary")?)
    )
    .unwrap();
    let domains = field(ir, "domains")?.as_object().ok_or("ESS IR: domains")?;
    for (domain_name, domain) in domains {
        let naming = field(domain, "naming")?;
        writeln!(
            page,
            "## {} domain\n\n`{domain_name}`. {}\n",
            text(naming, "display")?,
            prose(naming.get("summary").and_then(Value::as_str).unwrap_or(""))
        )
        .unwrap();
        let names = list(domain, "entities")?;
        // `DomainGraph` is registered globally by the docs-system product site; the graph is the
        // `b10x-domain-graph/1` document generated beside this page.
        writeln!(
            page,
            "### Entities and relations\n\n<DomainGraph data={{domainGraph}} />\n"
        )
        .unwrap();
        for name in names {
            let name = name.as_str().ok_or("ESS IR: entity name")?;
            render_entity(&mut page, model, field(field(ir, "entities")?, name)?)?;
        }
        for (key, label) in [
            ("commands", "Commands"),
            ("events", "Events"),
            ("errors", "Errors"),
            ("views", "Views"),
        ] {
            let declared = list(domain, key)?;
            writeln!(page, "### {label}\n").unwrap();
            if declared.is_empty() {
                writeln!(
                    page,
                    "The specification declares no {} yet.\n",
                    label.to_lowercase()
                )
                .unwrap();
            }
            for item in declared {
                let name = item
                    .as_str()
                    .ok_or_else(|| format!("ESS IR: {key} entry is not a name"))?;
                let declaration = field(field(ir, key)?, name)?;
                render_declaration(&mut page, model, key, declaration)?;
            }
        }
    }
    Ok(page.trim_end().to_string() + "\n")
}

/// Backticked names, comma-separated.
fn names(values: &[Value]) -> String {
    values
        .iter()
        .filter_map(Value::as_str)
        .map(|s| format!("`{s}`"))
        .collect::<Vec<_>>()
        .join(", ")
}

fn fields_table(page: &mut String, model: &Model, heading: &str, fields: &[Value]) -> Result<()> {
    if fields.is_empty() {
        return Ok(());
    }
    writeln!(page, "| {heading} | Type |\n|---|---|").unwrap();
    for f in fields {
        writeln!(
            page,
            "| `{}` | {} |",
            text(f, "name")?,
            model.type_ref(field(f, "type_ref")?, "./types.md")?
        )
        .unwrap();
    }
    page.push('\n');
    Ok(())
}

/// One command, event, error or view.
fn render_declaration(page: &mut String, model: &Model, key: &str, item: &Value) -> Result<()> {
    writeln!(page, "#### {}\n", model.short(text(item, "name")?)).unwrap();
    match key {
        "commands" => {
            fields_table(page, model, "Input", list(item, "input")?)?;
            page.push_str("| Outcome | When | Effect | Emits | Error |\n|---|---|---|---|---|\n");
            for outcome in list(item, "outcomes")? {
                let when = text(field(outcome, "condition")?, "kind")?.replace('_', " ");
                let effect = match outcome.get("subject") {
                    Some(subject) => {
                        let entity = model.short(text(subject, "entity")?);
                        let verb = text(subject, "effect")?;
                        match subject.get("transition") {
                            Some(t) => format!(
                                "{verb} {entity} by `{}`, from {} to `{}`",
                                text(t, "name")?,
                                names(list(t, "from")?),
                                text(t, "to")?
                            ),
                            None => format!("{verb} {entity}"),
                        }
                    }
                    None if outcome["complete_refusal"] == true => "refused".to_string(),
                    None => "none".to_string(),
                };
                let emits: Vec<_> = list(outcome, "emits")?
                    .iter()
                    .filter_map(Value::as_str)
                    .map(|e| format!("`{}`", model.short(e)))
                    .collect();
                let emits = if emits.is_empty() {
                    "none".to_string()
                } else {
                    emits.join(", ")
                };
                let error = outcome
                    .get("error")
                    .and_then(Value::as_str)
                    .map_or("none".to_string(), |e| format!("`{}`", model.short(e)));
                writeln!(
                    page,
                    "| `{}` | {when} | {effect} | {emits} | {error} |",
                    text(outcome, "name")?
                )
                .unwrap();
            }
            page.push('\n');
        }
        "views" => {
            writeln!(
                page,
                "Projects [{0}](#{1}); consistency `{2}`.\n",
                model.short(text(item, "source")?),
                slug(model.short(text(item, "source")?)),
                text(item, "consistency")?
            )
            .unwrap();
            fields_table(page, model, "Field", list(item, "fields")?)?;
        }
        _ => fields_table(page, model, "Field", list(item, "fields")?)?,
    }
    Ok(())
}

fn render_entity(page: &mut String, model: &Model, entity: &Value) -> Result<()> {
    let types = "./types.md";
    let name = model.short(text(entity, "name")?);
    let identity = field(entity, "identity")?;
    writeln!(
        page,
        "### {name}\n\nIdentity: `{}`, {}.\n",
        text(identity, "name")?,
        model.type_ref(field(identity, "type_ref")?, types)?
    )
    .unwrap();
    let fields = list(entity, "fields")?;
    if !fields.is_empty() {
        page.push_str("| Field | Type |\n|---|---|\n");
        for f in fields {
            writeln!(
                page,
                "| `{}` | {} |",
                text(f, "name")?,
                model.type_ref(field(f, "type_ref")?, types)?
            )
            .unwrap();
        }
        page.push('\n');
    }
    let lifecycle = field(entity, "lifecycle")?;
    let terminal = match lifecycle.get("terminal") {
        Some(_) => names(list(lifecycle, "terminal")?),
        None => "none".to_string(),
    };
    writeln!(
        page,
        "Lifecycle: states {}; initial `{}`; terminal {terminal}.\n",
        names(list(lifecycle, "states")?),
        text(lifecycle, "initial")?,
    )
    .unwrap();
    let transitions = lifecycle
        .get("transitions")
        .and_then(Value::as_array)
        .map(Vec::as_slice)
        .unwrap_or_default();
    if !transitions.is_empty() {
        page.push_str("| Transition | From | To |\n|---|---|---|\n");
        for t in transitions {
            writeln!(
                page,
                "| `{}` | {} | `{}` |",
                text(t, "name")?,
                names(list(t, "from")?),
                text(t, "to")?
            )
            .unwrap();
        }
        page.push('\n');
    }
    let relations = entity
        .get("relations")
        .and_then(Value::as_array)
        .map(Vec::as_slice)
        .unwrap_or_default();
    if !relations.is_empty() {
        page.push_str("| Relation | Kind | Target | Cardinality | Via |\n|---|---|---|---|---|\n");
        for r in relations {
            let target = model.short(text(r, "target")?);
            writeln!(
                page,
                "| `{}` | {} | [{target}](#{}) | {} | `{}` |",
                text(r, "name")?,
                text(r, "kind")?,
                slug(target),
                text(r, "cardinality")?,
                text(r, "via")?
            )
            .unwrap();
        }
        page.push('\n');
    }
    for invariant in list(entity, "invariants")? {
        writeln!(page, "- Invariant: `{}`", prose(&invariant.to_string())).unwrap();
    }
    Ok(())
}

fn render_types(model: &Model) -> Result<String> {
    let ir = model.ir;
    let mut page = header(
        "Value types",
        "Every value type the Commission specification declares: unions, structs, enums and identifiers.",
        ir,
    )?;
    page.push_str(
        "# Value types\n\nThe types the ports speak and the entities' identifiers. Each entity's \
         lifecycle states are listed with the entity on the [domain model](./domain-model.md) page.\n\n",
    );
    let types = field(ir, "types")?.as_object().ok_or("ESS IR: types")?;
    for (kind, label) in [
        ("union", "Unions"),
        ("struct", "Structs"),
        ("enum", "Enums"),
        ("newtype", "Identifiers and wrapped values"),
    ] {
        let members: Vec<_> = types
            .iter()
            .filter(|(name, t)| model.is_type(name) && t["body"]["kind"] == kind)
            .collect();
        if members.is_empty() {
            continue;
        }
        writeln!(page, "## {label}\n").unwrap();
        for (name, declared) in members {
            let short = model.short(name);
            if short == "Unit" {
                continue;
            }
            let body = field(declared, "body")?;
            writeln!(page, "### {short}\n").unwrap();
            match kind {
                "union" => {
                    writeln!(
                        page,
                        "Tagged by `{}`.\n\n| Variant | Payload |\n|---|---|",
                        text(body, "tag")?
                    )
                    .unwrap();
                    let variants = field(body, "variants")?
                        .as_object()
                        .ok_or("ESS IR: union variants")?;
                    for (variant, payload) in variants {
                        writeln!(page, "| `{variant}` | {} |", model.type_ref(payload, "")?)
                            .unwrap();
                    }
                }
                "struct" => {
                    page.push_str("| Field | Type |\n|---|---|\n");
                    for f in list(body, "fields")? {
                        writeln!(
                            page,
                            "| `{}` | {} |",
                            text(f, "name")?,
                            model.type_ref(field(f, "type_ref")?, "")?
                        )
                        .unwrap();
                    }
                }
                "enum" => {
                    let variants: Vec<_> = list(body, "variants")?
                        .iter()
                        .filter_map(Value::as_str)
                        .map(|v| format!("`{v}`"))
                        .collect();
                    writeln!(page, "Variants: {}.", variants.join(", ")).unwrap();
                }
                _ => {
                    writeln!(page, "Wraps {}.", model.type_ref(field(body, "of")?, "")?).unwrap();
                }
            }
            page.push('\n');
        }
    }
    Ok(page.trim_end().to_string() + "\n")
}

/// A type reference in the domain graph's notation: `AgentId`, `integer`, `List<ObservationId>`.
fn type_name(model: &Model, reference: &Value) -> Result<String> {
    Ok(match text(reference, "kind")? {
        "primitive" => text(reference, "name")?.to_string(),
        "declared" => model.short(text(reference, "name")?).to_string(),
        "optional" => format!("Optional<{}>", type_name(model, field(reference, "of")?)?),
        "list" => format!("List<{}>", type_name(model, field(reference, "of")?)?),
        other => return Err(format!("ESS IR: unsupported type reference kind `{other}`")),
    })
}

fn graph_field(model: &Model, f: &Value) -> Result<Value> {
    Ok(json!({"name": text(f, "name")?, "type": type_name(model, field(f, "type_ref")?)?}))
}

/// The `b10x-domain-graph/1` document for the specification's one domain.
fn render_domain_graph(model: &Model, source: Option<&str>) -> Result<String> {
    let ir = model.ir;
    let domains = field(ir, "domains")?.as_object().ok_or("ESS IR: domains")?;
    let [(domain_id, domain)] = domains.iter().collect::<Vec<_>>()[..] else {
        return Err(format!(
            "the domain graph covers one domain; the specification declares {}",
            domains.len()
        ));
    };
    let mut commands = Vec::new();
    for name in list(domain, "commands")? {
        let name = name.as_str().ok_or("ESS IR: command name")?;
        commands.push((model.short(name), field(field(ir, "commands")?, name)?));
    }
    // The commands with an outcome that has `effect` on `entity` (through `transition`, if given).
    let commands_for = |entity: &str, effect: &str, transition: Option<&str>| -> Vec<Value> {
        let mut found: Vec<Value> = Vec::new();
        for (short, command) in &commands {
            let hit = command["outcomes"]
                .as_array()
                .into_iter()
                .flatten()
                .any(|o| {
                    let s = &o["subject"];
                    s["entity"] == entity
                        && s["effect"] == effect
                        && transition.is_none_or(|t| s["transition"]["name"] == t)
                });
            if hit && !found.iter().any(|v| v == short) {
                found.push(Value::from(*short));
            }
        }
        found
    };
    let mut names: Vec<&str> = list(domain, "entities")?
        .iter()
        .map(|n| n.as_str().ok_or("ESS IR: entity name"))
        .collect::<std::result::Result<_, _>>()?;
    names.sort_unstable();
    let mut entities = Vec::new();
    let mut relations = Vec::new();
    for name in names {
        let entity = field(field(ir, "entities")?, name)?;
        let identity = field(entity, "identity")?;
        let fields = list(entity, "fields")?
            .iter()
            .map(|f| graph_field(model, f))
            .collect::<Result<Vec<_>>>()?;
        let mut node = json!({
            "id": name,
            "name": model.short(name),
            "identity": graph_field(model, identity)?,
            "fields": fields,
        });
        if let Some(lifecycle) = entity.get("lifecycle") {
            let mut shape = json!({
                "initial": text(lifecycle, "initial")?,
                "states": field(lifecycle, "states")?,
            });
            if let Some(terminal) = lifecycle.get("terminal") {
                shape["terminal"] = terminal.clone();
            }
            if let Some(transitions) = lifecycle.get("transitions").and_then(Value::as_array) {
                let mut out = Vec::new();
                for t in transitions {
                    let mut transition = json!({
                        "name": text(t, "name")?,
                        "from": field(t, "from")?,
                        "to": text(t, "to")?,
                    });
                    let by = commands_for(name, "moves", Some(text(t, "name")?));
                    if !by.is_empty() {
                        transition["commands"] = Value::from(by);
                    }
                    out.push(transition);
                }
                shape["transitions"] = Value::from(out);
            }
            node["lifecycle"] = shape;
        }
        let created = commands_for(name, "creates", None);
        if !created.is_empty() {
            node["createdBy"] = Value::from(created);
        }
        entities.push(node);
        for r in entity
            .get("relations")
            .and_then(Value::as_array)
            .into_iter()
            .flatten()
        {
            let mut relation = json!({
                "from": name,
                "to": text(r, "target")?,
                "name": text(r, "name")?,
                "kind": text(r, "kind")?,
                "cardinality": text(r, "cardinality")?,
            });
            if let Some(via) = r.get("via").and_then(Value::as_str) {
                relation["via"] = Value::from(via);
            }
            relations.push(relation);
        }
    }
    let naming = field(domain, "naming")?;
    let mut domain_node = json!({"id": domain_id});
    for (key, value) in [
        ("display", naming.get("display")),
        ("summary", naming.get("summary")),
        ("system", ir.get("system")),
    ] {
        if let Some(value) = value.and_then(Value::as_str) {
            domain_node[key] = Value::from(value);
        }
    }
    if let Some(source) = source {
        domain_node["source"] = Value::from(source);
    }
    let graph = json!({
        "format": "b10x-domain-graph/1",
        "domain": domain_node,
        "entities": entities,
        "relations": relations,
    });
    Ok(serde_json::to_string_pretty(&graph).map_err(|e| e.to_string())? + "\n")
}

fn render(ir: &Value, source: Option<&str>) -> Result<Pages> {
    let model = Model::new(ir)?;
    Ok(Pages::from([
        (DOMAIN_MODEL, render_domain_model(&model)?),
        (DOMAIN_GRAPH, render_domain_graph(&model, source)?),
        (TYPES, render_types(&model)?),
    ]))
}

/// Write the pages, or with `check` compare them; either way, refuse a page nothing generates.
fn apply(dir: &Path, pages: &Pages, check: bool) -> Result<()> {
    let mut problems = Vec::new();
    if dir.exists() {
        for entry in fs::read_dir(dir).map_err(|e| format!("{}: {e}", dir.display()))? {
            let name = entry.map_err(|e| e.to_string())?.file_name();
            let name = name.to_string_lossy();
            if !pages.contains_key(name.as_ref()) {
                problems.push(format!(
                    "{name}: not generated; reference/ holds generated pages only"
                ));
            }
        }
    }
    for (name, content) in pages {
        let path = dir.join(name);
        if check {
            match fs::read_to_string(&path) {
                Ok(current) if current == *content => {}
                Ok(_) => problems.push(format!("{name}: differs from a fresh generation")),
                Err(_) => problems.push(format!("{name}: missing")),
            }
        } else {
            fs::create_dir_all(dir).map_err(|e| format!("{}: {e}", dir.display()))?;
            fs::write(&path, content).map_err(|e| format!("{}: {e}", path.display()))?;
        }
    }
    if problems.is_empty() {
        Ok(())
    } else {
        Err(format!(
            "{} is stale:\n  {}\nrun `task docs`",
            dir.display(),
            problems.join("\n  ")
        ))
    }
}

fn run(cli: Cli) -> Result<String> {
    let (check, root, ess, ir) = match cli.command {
        Action::Generate {
            check,
            root,
            ess,
            ir,
        } => (check, root, ess, ir),
        Action::Provenance { site, commit } => {
            let path = provenance(&site, &commit)?;
            return Ok(format!("site provenance written to {}", path.display()));
        }
    };
    let (ir, source) = match ir {
        Some(path) => (
            serde_json::from_slice(
                &fs::read(&path).map_err(|e| format!("{}: {e}", path.display()))?,
            )
            .map_err(|e| format!("{}: {e}", path.display()))?,
            None,
        ),
        None => {
            let ir = compile_ir(&root, &ess)?;
            let source = format!(
                "{} ess/ compiled with {}",
                text(&ir, "system")?,
                ess_version(&ess)?
            );
            (ir, Some(source))
        }
    };
    let pages = render(&ir, source.as_deref())?;
    let dir = root.join(REFERENCE_DIR);
    apply(&dir, &pages, check)?;
    let raw = raw_admonitions(&root.join(DOCS_DIR))?;
    if !raw.is_empty() {
        return Err(format!(
            "raw admonition titles (`:::kind Title`; write `:::kind[Title]`):\n  {}",
            raw.join("\n  ")
        ));
    }
    let verb = if check { "current" } else { "written" };
    Ok(format!(
        "{} reference pages {verb} in {}",
        pages.len(),
        dir.display()
    ))
}

fn main() -> ExitCode {
    match run(Cli::parse()) {
        Ok(message) => {
            println!("commission-docs: {message}");
            ExitCode::SUCCESS
        }
        Err(error) => {
            eprintln!("commission-docs: {error}");
            ExitCode::FAILURE
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    fn fixture() -> Value {
        json!({
            "system": "demo", "version": 1, "summary": "A {demo} <system>.",
            "domains": {"demo.core": {
                "naming": {"display": "Core", "summary": "The core."},
                "entities": ["demo.core.Case", "demo.core.Run"],
                "commands": ["demo.core.Close"], "events": [], "errors": [], "views": []
            }},
            "types": {
                "demo.core.CaseId": {"body": {"kind": "newtype", "of": {"kind": "primitive", "name": "string"}}},
                "demo.core.Unit": {"body": {"kind": "newtype", "of": {"kind": "primitive", "name": "boolean"}}},
                "demo.core.Case.State": {"body": {"kind": "enum", "variants": ["Open"]}},
                "demo.core.Truth": {"body": {"kind": "enum", "variants": ["True", "False"]}},
                "demo.core.Outcome": {"body": {"kind": "union", "tag": "kind", "variants": {
                    "Done": {"kind": "declared", "name": "demo.core.Unit"},
                    "Waiting": {"kind": "list", "of": {"kind": "declared", "name": "demo.core.CaseId"}}
                }}}
            },
            "commands": {"demo.core.Close": {"name": "demo.core.Close",
                "input": [{"name": "case_id", "type_ref": {"kind": "declared", "name": "demo.core.CaseId"}}],
                "outcomes": [
                    {"name": "closed", "condition": {"kind": "otherwise"}, "emits": [],
                     "subject": {"entity": "demo.core.Case", "effect": "moves",
                                 "transition": {"name": "close", "from": ["Open"], "to": "Closed"}}},
                    {"name": "wrong-state", "condition": {"kind": "wrong_state"}, "complete_refusal": true,
                     "emits": [], "error": "demo.core.Conflict"}
                ]}},
            "entities": {
                "demo.core.Case": {
                    "name": "demo.core.Case",
                    "identity": {"name": "case_id", "type_ref": {"kind": "declared", "name": "demo.core.CaseId"}},
                    "fields": [{"name": "truth", "type_ref": {"kind": "optional", "of": {"kind": "declared", "name": "demo.core.Truth"}}}],
                    "lifecycle": {"states": ["Open", "Closed"], "initial": "Open", "transitions": [{"name": "close", "from": ["Open"], "to": "Closed"}]},
                    "invariants": [],
                    "relations": [{"name": "runs", "kind": "owns", "target": "demo.core.Run", "cardinality": "many", "via": "case_id"}]
                },
                "demo.core.Run": {
                    "name": "demo.core.Run",
                    "identity": {"name": "run_id", "type_ref": {"kind": "primitive", "name": "uuid"}},
                    "fields": [],
                    "lifecycle": {"states": ["Running"], "initial": "Running", "terminal": ["Running"]},
                    "invariants": []
                }
            }
        })
    }

    fn scratch(label: &str) -> PathBuf {
        let dir =
            std::env::temp_dir().join(format!("commission-docs-{label}-{}", std::process::id()));
        let _ = fs::remove_dir_all(&dir);
        dir
    }

    #[test]
    fn pages_carry_the_marker_the_model_and_the_absence_of_commands() {
        let pages = render(&fixture(), None).expect("renders");
        let model = &pages[DOMAIN_MODEL];
        assert!(model.starts_with("---\ntitle: \"Domain model\"\ndescription: \""));
        assert!(model.contains(MARKER));
        assert!(model.contains("A \\{demo\\} &lt;system&gt;."));
        assert!(model.contains("import domainGraph from './domain-graph.json';"));
        assert!(model.contains("<DomainGraph data={domainGraph} />"));
        assert!(!model.contains("mermaid"));
        assert!(model.contains("| `truth` | optional [`Truth`](./types.md#truth) |"));
        assert!(model.contains("The specification declares no events yet."));
        assert!(model.contains("terminal none."));
        assert!(model.contains("| `close` | `Open` | `Closed` |"));
        assert!(model.contains("| `closed` | otherwise | moves Case by `close`, from `Open` to `Closed` | none | none |"));
        assert!(model.contains("| `wrong-state` | wrong state | refused | none | `Conflict` |"));
        let types = &pages[TYPES];
        assert!(types.contains(MARKER));
        assert!(types.contains("| `Done` | none |"));
        assert!(types.contains("| `Waiting` | list of [`CaseId`](#caseid) |"));
        assert!(!types.contains("### Case.State") && !types.contains("### Unit"));
    }

    #[test]
    fn provenance_binds_the_built_site_to_a_full_commit() {
        let site = scratch("provenance");
        let commit = "1d0f4fcd58405f4890225d28788577cdecf4ed9f";
        assert!(provenance(&site, commit).is_err(), "no built site");
        fs::create_dir_all(&site).unwrap();
        fs::write(site.join("index.html"), "<!doctype html>").unwrap();
        assert!(provenance(&site, "abc").is_err());
        assert!(provenance(&site, &"0".repeat(40)).is_err());
        let path = provenance(&site, commit).expect("writes");
        let written: Value = serde_json::from_slice(&fs::read(path).unwrap()).unwrap();
        assert_eq!(
            written,
            json!({"schema": "b10x-project-site/v1", "repository": "commission",
                   "commit": commit, "baseUrl": "/commission/"})
        );
        assert!(site.join(".nojekyll").is_file());
        fs::remove_dir_all(&site).unwrap();
    }

    #[test]
    fn raw_admonition_titles_are_found_and_bracket_titles_pass() {
        assert!(is_raw_admonition(":::note Generated page"));
        assert!(is_raw_admonition(":::caution  x"));
        assert!(!is_raw_admonition(":::note[Generated page]"));
        assert!(!is_raw_admonition(":::note"));
        assert!(!is_raw_admonition(":::note   "));
        assert!(!is_raw_admonition(":::"));
        assert!(!is_raw_admonition("  :::note Title"));
        assert!(!is_raw_admonition(":::Note Title"));

        let dir = scratch("admonitions");
        fs::create_dir_all(dir.join("concepts")).unwrap();
        fs::write(dir.join("ok.md"), ":::info[Fine]\n\nbody\n\n:::\n").unwrap();
        fs::write(dir.join("concepts/bad.mdx"), "# T\n\n:::tip Raw\n:::\n").unwrap();
        fs::write(dir.join("notes.txt"), ":::tip Not markdown\n").unwrap();
        let found = raw_admonitions(&dir).unwrap();
        assert_eq!(found.len(), 1, "{found:?}");
        assert!(found[0].ends_with("bad.mdx:3"), "{found:?}");
        fs::remove_dir_all(&dir).unwrap();
    }

    #[test]
    fn rendering_is_deterministic() {
        assert_eq!(render(&fixture(), None), render(&fixture(), None));
    }

    #[test]
    fn an_unknown_type_reference_is_refused() {
        let mut ir = fixture();
        ir["entities"]["demo.core.Run"]["identity"]["type_ref"] = json!({"kind": "map"});
        assert!(
            render(&ir, None)
                .unwrap_err()
                .contains("unsupported type reference kind")
        );
    }

    #[test]
    fn the_domain_graph_carries_entities_lifecycles_commands_and_relations() {
        let pages = render(&fixture(), Some("demo ess/ compiled with ess 0.0.0")).unwrap();
        let graph: Value = serde_json::from_str(&pages[DOMAIN_GRAPH]).unwrap();
        assert_eq!(graph["format"], "b10x-domain-graph/1");
        assert_eq!(graph["domain"]["id"], "demo.core");
        assert_eq!(
            graph["domain"]["source"],
            "demo ess/ compiled with ess 0.0.0"
        );
        let names: Vec<_> = graph["entities"]
            .as_array()
            .unwrap()
            .iter()
            .map(|e| e["name"].clone())
            .collect();
        assert_eq!(names, [json!("Case"), json!("Run")]);
        let case = &graph["entities"][0];
        assert_eq!(
            case["identity"],
            json!({"name": "case_id", "type": "CaseId"})
        );
        assert_eq!(case["fields"][0]["type"], "Optional<Truth>");
        assert_eq!(
            case["lifecycle"]["transitions"][0],
            json!({"name": "close", "from": ["Open"], "to": "Closed", "commands": ["Close"]})
        );
        assert!(case["lifecycle"].get("terminal").is_none());
        assert_eq!(
            graph["relations"],
            json!([{"from": "demo.core.Case", "to": "demo.core.Run", "name": "runs",
                    "kind": "owns", "cardinality": "many", "via": "case_id"}])
        );
        let unsourced: Value =
            serde_json::from_str(&render(&fixture(), None).unwrap()[DOMAIN_GRAPH]).unwrap();
        assert!(unsourced["domain"].get("source").is_none());
    }

    #[test]
    fn a_specification_with_two_domains_is_refused() {
        let mut ir = fixture();
        ir["domains"]["demo.other"] = ir["domains"]["demo.core"].clone();
        assert!(render(&ir, None).unwrap_err().contains("covers one domain"));
    }

    #[test]
    fn check_fails_after_a_hand_edit_a_removal_or_a_stray_page() {
        let dir = scratch("check");
        let pages = render(&fixture(), None).expect("renders");
        assert!(
            apply(&dir, &pages, true).is_err(),
            "missing pages are stale"
        );
        apply(&dir, &pages, false).expect("writes");
        apply(&dir, &pages, true).expect("fresh pages are current");

        let edited = dir.join(TYPES);
        fs::write(&edited, pages[TYPES].replace("Variants", "Values")).unwrap();
        let error = apply(&dir, &pages, true).unwrap_err();
        assert!(error.contains("types.md: differs"), "{error}");

        apply(&dir, &pages, false).expect("regenerates");
        fs::write(dir.join("notes.md"), "# hand-written\n").unwrap();
        let error = apply(&dir, &pages, true).unwrap_err();
        assert!(error.contains("notes.md: not generated"), "{error}");
        fs::remove_dir_all(&dir).unwrap();
    }
}
