import type {Config} from '@docusaurus/types';
import type * as Preset from '@docusaurus/preset-classic';
import {withProductSite} from '@beyond10x/docs-system/product-site';

// Pages under docs/reference/ and files under data/ are generated by `loom-docs generate`;
// everything else is written by hand.
const config: Config = {
  title: 'Loom',
  tagline: 'The native agent harness: a model that acts, only inside its frontier.',
  favicon: 'img/mark.svg',

  future: {
    v4: true,
  },

  url: 'https://beyond10x.github.io',
  baseUrl: '/loom/',

  organizationName: 'beyond10x',
  projectName: 'loom',
  deploymentBranch: 'gh-pages',
  trailingSlash: false,

  onBrokenLinks: 'throw',
  onBrokenAnchors: 'throw',

  markdown: {
    format: 'detect',
    hooks: {
      onBrokenMarkdownLinks: 'throw',
    },
    mermaid: true,
  },

  themes: ['@docusaurus/theme-mermaid'],
  plugins: [
    [
      '@docusaurus/plugin-client-redirects',
      {
        // The documentation lived at the site root until the landing page took it.
        createRedirects(existingPath: string) {
          if (existingPath.startsWith('/docs/')) return [existingPath.slice('/docs'.length)];
          return undefined;
        },
      },
    ],
  ],

  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
  },

  presets: [
    [
      'classic',
      {
        docs: {
          sidebarPath: './sidebars.ts',
          routeBasePath: 'docs',
          editUrl: 'https://github.com/beyond10x/loom/tree/main/website/',
        },
        blog: false,
      } satisfies Preset.Options,
    ],
  ],

  themeConfig: {
    navbar: {
      title: 'Loom',
      items: [
        {to: '/docs/', label: 'Documentation', position: 'left'},
        {to: '/docs/reference/ess', label: 'Specification', position: 'left'},
        {to: '/docs/status', label: 'Status', position: 'left'},
        {href: 'https://github.com/beyond10x/loom', label: 'GitHub ↗', position: 'right'},
      ],
    },
    footer: {
      links: [
        {
          title: 'Documentation',
          items: [
            {label: 'Overview', to: '/docs/'},
            {label: 'One run, five steps', to: '/docs/concepts/one-run'},
            {label: 'Action selection', to: '/docs/concepts/action-selection'},
            {label: 'Where Loom ends', to: '/docs/concepts/where-loom-ends'},
            {label: 'ESS specification', to: '/docs/reference/ess'},
            {label: 'Status', to: '/docs/status'},
          ],
        },
        {
          title: 'Family',
          items: [
            {label: 'ELS', href: 'https://beyond10x.github.io/els/'},
            {label: 'Commission', href: 'https://beyond10x.github.io/commission/'},
            {label: 'ESS', href: 'https://beyond10x.github.io/ess/'},
          ],
        },
        {
          title: 'Project',
          items: [{label: 'Source', href: 'https://github.com/beyond10x/loom'}],
        },
      ],
      copyright: 'A beyond10x project. Loom · Apache-2.0.',
    },
  } satisfies Preset.ThemeConfig,
};

export default withProductSite(config, {landing: './product.json', product: 'loom'});
