import type {Config} from '@docusaurus/types';
import type * as Preset from '@docusaurus/preset-classic';
import {themes as prismThemes} from 'prism-react-renderer';
import docsSystemPlugin, {ecosystemFooterGroup, ecosystemNavbarItems} from '@beyond10x/docs-system/docusaurus';

// Pages under docs/reference/ are generated by `loom-docs generate`; everything else is written by hand.
const config: Config = {
  title: 'Loom',
  tagline: 'The native agent harness: a model that acts, only inside its frontier.',
  favicon: 'img/mark.svg',

  future: {
    v4: true,
  },

  url: 'https://beyond10x.github.io',
  baseUrl: '/loom/',

  organizationName: 'beyond10x',
  projectName: 'loom',
  deploymentBranch: 'gh-pages',
  trailingSlash: false,

  onBrokenLinks: 'throw',

  markdown: {
    format: 'detect',
    hooks: {
      onBrokenMarkdownLinks: 'throw',
    },
    mermaid: true,
  },

  themes: ['@docusaurus/theme-mermaid'],
  plugins: [docsSystemPlugin],

  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
  },

  presets: [
    [
      'classic',
      {
        docs: {
          sidebarPath: './sidebars.ts',
          routeBasePath: '/',
          editUrl: 'https://github.com/beyond10x/loom/tree/main/website/',
        },
        blog: false,
        theme: {
          customCss: './src/css/custom.css',
        },
      } satisfies Preset.Options,
    ],
  ],

  themeConfig: {
    colorMode: {
      respectPrefersColorScheme: true,
    },
    navbar: {
      title: 'Loom',
      logo: {
        alt: 'Loom',
        src: 'img/mark.svg',
        width: 26,
        height: 26,
      },
      items: [
        ...ecosystemNavbarItems(),
        {
          type: 'docSidebar',
          sidebarId: 'docsSidebar',
          position: 'left',
          label: 'Documentation',
        },
        {to: '/status', label: 'Status', position: 'left'},
        {
          href: 'https://github.com/beyond10x/loom',
          label: 'GitHub',
          position: 'right',
        },
      ],
    },
    footer: {
      style: 'dark',
      links: [
        ecosystemFooterGroup(),
        {
          title: 'Documentation',
          items: [
            {label: 'Overview', to: '/'},
            {label: 'One run, five steps', to: '/concepts/one-run'},
            {label: 'Action selection', to: '/concepts/action-selection'},
            {label: 'Where Loom ends', to: '/concepts/where-loom-ends'},
            {label: 'ESS specification', to: '/reference/ess'},
          ],
        },
        {
          title: 'Project',
          items: [
            {label: 'Status', to: '/status'},
            {label: 'Source', href: 'https://github.com/beyond10x/loom'},
          ],
        },
      ],
      copyright: 'Loom · Apache-2.0 · built with Docusaurus.',
    },
    prism: {
      theme: prismThemes.github,
      darkTheme: prismThemes.dracula,
      additionalLanguages: ['rust', 'yaml', 'json', 'bash'],
    },
    mermaid: {
      theme: {light: 'neutral', dark: 'dark'},
    },
  } satisfies Preset.ThemeConfig,
};

export default config;
