import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Start here',
      collapsed: false,
      items: ['index', 'status'],
    },
    {
      type: 'category',
      label: 'Concepts',
      collapsed: false,
      items: [
        'concepts/one-run',
        'concepts/action-selection',
        'concepts/fast-selector',
        'concepts/commission-and-harness',
        'concepts/where-loom-ends',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'reference'}],
    },
  ],
};

export default sidebars;
